// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: limitswitch/v1/limit_switch.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLimitSwitch1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitSwitch1Request) Reset() {
	*x = GetLimitSwitch1Request{}
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitSwitch1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitSwitch1Request) ProtoMessage() {}

func (x *GetLimitSwitch1Request) ProtoReflect() protoreflect.Message {
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitSwitch1Request.ProtoReflect.Descriptor instead.
func (*GetLimitSwitch1Request) Descriptor() ([]byte, []int) {
	return file_limitswitch_v1_limit_switch_proto_rawDescGZIP(), []int{0}
}

type GetLimitSwitch1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPressed     bool                   `protobuf:"varint,1,opt,name=is_pressed,json=isPressed,proto3" json:"is_pressed,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLimitSwitch1Response) Reset() {
	*x = GetLimitSwitch1Response{}
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLimitSwitch1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLimitSwitch1Response) ProtoMessage() {}

func (x *GetLimitSwitch1Response) ProtoReflect() protoreflect.Message {
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLimitSwitch1Response.ProtoReflect.Descriptor instead.
func (*GetLimitSwitch1Response) Descriptor() ([]byte, []int) {
	return file_limitswitch_v1_limit_switch_proto_rawDescGZIP(), []int{1}
}

func (x *GetLimitSwitch1Response) GetIsPressed() bool {
	if x != nil {
		return x.IsPressed
	}
	return false
}

func (x *GetLimitSwitch1Response) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StreamLimitSwitch1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLimitSwitch1Request) Reset() {
	*x = StreamLimitSwitch1Request{}
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLimitSwitch1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLimitSwitch1Request) ProtoMessage() {}

func (x *StreamLimitSwitch1Request) ProtoReflect() protoreflect.Message {
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLimitSwitch1Request.ProtoReflect.Descriptor instead.
func (*StreamLimitSwitch1Request) Descriptor() ([]byte, []int) {
	return file_limitswitch_v1_limit_switch_proto_rawDescGZIP(), []int{2}
}

type StreamLimitSwitch1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPressed     bool                   `protobuf:"varint,1,opt,name=is_pressed,json=isPressed,proto3" json:"is_pressed,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLimitSwitch1Response) Reset() {
	*x = StreamLimitSwitch1Response{}
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLimitSwitch1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLimitSwitch1Response) ProtoMessage() {}

func (x *StreamLimitSwitch1Response) ProtoReflect() protoreflect.Message {
	mi := &file_limitswitch_v1_limit_switch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLimitSwitch1Response.ProtoReflect.Descriptor instead.
func (*StreamLimitSwitch1Response) Descriptor() ([]byte, []int) {
	return file_limitswitch_v1_limit_switch_proto_rawDescGZIP(), []int{3}
}

func (x *StreamLimitSwitch1Response) GetIsPressed() bool {
	if x != nil {
		return x.IsPressed
	}
	return false
}

func (x *StreamLimitSwitch1Response) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_limitswitch_v1_limit_switch_proto protoreflect.FileDescriptor

const file_limitswitch_v1_limit_switch_proto_rawDesc = "" +
	"\n" +
	"!limitswitch/v1/limit_switch.proto\x12\x0elimitswitch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x16GetLimitSwitch1Request\"s\n" +
	"\x17GetLimitSwitch1Response\x12\x1d\n" +
	"\n" +
	"is_pressed\x18\x01 \x01(\bR\tisPressed\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1b\n" +
	"\x19StreamLimitSwitch1Request\"v\n" +
	"\x1aStreamLimitSwitch1Response\x12\x1d\n" +
	"\n" +
	"is_pressed\x18\x01 \x01(\bR\tisPressed\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB+Z)github.com/tbe-team/raybot/limitswitch/v1b\x06proto3"

var (
	file_limitswitch_v1_limit_switch_proto_rawDescOnce sync.Once
	file_limitswitch_v1_limit_switch_proto_rawDescData []byte
)

func file_limitswitch_v1_limit_switch_proto_rawDescGZIP() []byte {
	file_limitswitch_v1_limit_switch_proto_rawDescOnce.Do(func() {
		file_limitswitch_v1_limit_switch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limitswitch_v1_limit_switch_proto_rawDesc), len(file_limitswitch_v1_limit_switch_proto_rawDesc)))
	})
	return file_limitswitch_v1_limit_switch_proto_rawDescData
}

var file_limitswitch_v1_limit_switch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_limitswitch_v1_limit_switch_proto_goTypes = []any{
	(*GetLimitSwitch1Request)(nil),     // 0: limitswitch.v1.GetLimitSwitch1Request
	(*GetLimitSwitch1Response)(nil),    // 1: limitswitch.v1.GetLimitSwitch1Response
	(*StreamLimitSwitch1Request)(nil),  // 2: limitswitch.v1.StreamLimitSwitch1Request
	(*StreamLimitSwitch1Response)(nil), // 3: limitswitch.v1.StreamLimitSwitch1Response
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_limitswitch_v1_limit_switch_proto_depIdxs = []int32{
	4, // 0: limitswitch.v1.GetLimitSwitch1Response.updated_at:type_name -> google.protobuf.Timestamp
	4, // 1: limitswitch.v1.StreamLimitSwitch1Response.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_limitswitch_v1_limit_switch_proto_init() }
func file_limitswitch_v1_limit_switch_proto_init() {
	if File_limitswitch_v1_limit_switch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limitswitch_v1_limit_switch_proto_rawDesc), len(file_limitswitch_v1_limit_switch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_limitswitch_v1_limit_switch_proto_goTypes,
		DependencyIndexes: file_limitswitch_v1_limit_switch_proto_depIdxs,
		MessageInfos:      file_limitswitch_v1_limit_switch_proto_msgTypes,
	}.Build()
	File_limitswitch_v1_limit_switch_proto = out.File
	file_limitswitch_v1_limit_switch_proto_goTypes = nil
	file_limitswitch_v1_limit_switch_proto_depIdxs = nil
}
