# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.raybot import motor_pb2 as proto_dot_raybot_dot_motor__pb2


class DriveMotorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetConfig = channel.unary_unary(
                '/motor.DriveMotorService/SetConfig',
                request_serializer=proto_dot_raybot_dot_motor__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=proto_dot_raybot_dot_motor__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/motor.DriveMotorService/StreamStatus',
                request_serializer=proto_dot_raybot_dot_motor__pb2.StreamStatusRequest.SerializeToString,
                response_deserializer=proto_dot_raybot_dot_motor__pb2.StreamStatusResponse.FromString,
                _registered_method=True)


class DriveMotorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Server streaming: gửi trạng thái motor liên tục về client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriveMotorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=proto_dot_raybot_dot_motor__pb2.SetConfigRequest.FromString,
                    response_serializer=proto_dot_raybot_dot_motor__pb2.SetConfigResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=proto_dot_raybot_dot_motor__pb2.StreamStatusRequest.FromString,
                    response_serializer=proto_dot_raybot_dot_motor__pb2.StreamStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'motor.DriveMotorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('motor.DriveMotorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriveMotorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/motor.DriveMotorService/SetConfig',
            proto_dot_raybot_dot_motor__pb2.SetConfigRequest.SerializeToString,
            proto_dot_raybot_dot_motor__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/motor.DriveMotorService/StreamStatus',
            proto_dot_raybot_dot_motor__pb2.StreamStatusRequest.SerializeToString,
            proto_dot_raybot_dot_motor__pb2.StreamStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
