# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raybot/v1/drive_motor.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'raybot/v1/drive_motor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1braybot/v1/drive_motor.proto\x12\traybot.v1\"\xe6\x01\n!SetDriveMotorConfigurationRequest\x12\x14\n\x05speed\x18\x01 \x01(\rR\x05speed\x12T\n\tdirection\x18\x02 \x01(\x0e\x32\x36.raybot.v1.SetDriveMotorConfigurationRequest.DirectionR\tdirection\"U\n\tDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x15\n\x11\x44IRECTION_FORWARD\x10\x01\x12\x16\n\x12\x44IRECTION_BACKWARD\x10\x02\"$\n\"SetDriveMotorConfigurationResponse2\x90\x01\n\x11\x44riveMotorService\x12{\n\x1aSetDriveMotorConfiguration\x12,.raybot.v1.SetDriveMotorConfigurationRequest\x1a-.raybot.v1.SetDriveMotorConfigurationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raybot.v1.drive_motor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETDRIVEMOTORCONFIGURATIONREQUEST']._serialized_start=43
  _globals['_SETDRIVEMOTORCONFIGURATIONREQUEST']._serialized_end=273
  _globals['_SETDRIVEMOTORCONFIGURATIONREQUEST_DIRECTION']._serialized_start=188
  _globals['_SETDRIVEMOTORCONFIGURATIONREQUEST_DIRECTION']._serialized_end=273
  _globals['_SETDRIVEMOTORCONFIGURATIONRESPONSE']._serialized_start=275
  _globals['_SETDRIVEMOTORCONFIGURATIONRESPONSE']._serialized_end=311
  _globals['_DRIVEMOTORSERVICE']._serialized_start=314
  _globals['_DRIVEMOTORSERVICE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
