# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raybot/v1/lift_motor.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'raybot/v1/lift_motor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1araybot/v1/lift_motor.proto\x12\traybot.v1\"\xe1\x01\n SetLiftMotorConfigurationRequest\x12\x1a\n\x08\x64istance\x18\x01 \x01(\x01R\x08\x64istance\x12S\n\tdirection\x18\x02 \x01(\x0e\x32\x35.raybot.v1.SetLiftMotorConfigurationRequest.DirectionR\tdirection\"L\n\tDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x44IRECTION_UP\x10\x01\x12\x12\n\x0e\x44IRECTION_DOWN\x10\x02\"#\n!SetLiftMotorConfigurationResponse2\x8c\x01\n\x10LiftMotorService\x12x\n\x19SetLiftMotorConfiguration\x12+.raybot.v1.SetLiftMotorConfigurationRequest\x1a,.raybot.v1.SetLiftMotorConfigurationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raybot.v1.lift_motor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETLIFTMOTORCONFIGURATIONREQUEST']._serialized_start=42
  _globals['_SETLIFTMOTORCONFIGURATIONREQUEST']._serialized_end=267
  _globals['_SETLIFTMOTORCONFIGURATIONREQUEST_DIRECTION']._serialized_start=191
  _globals['_SETLIFTMOTORCONFIGURATIONREQUEST_DIRECTION']._serialized_end=267
  _globals['_SETLIFTMOTORCONFIGURATIONRESPONSE']._serialized_start=269
  _globals['_SETLIFTMOTORCONFIGURATIONRESPONSE']._serialized_end=304
  _globals['_LIFTMOTORSERVICE']._serialized_start=307
  _globals['_LIFTMOTORSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
