# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raybot/v1/state.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'raybot/v1/state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15raybot/v1/state.proto\x12\traybot.v1\"\x16\n\x14GetRobotStateRequest\"O\n\x15GetRobotStateResponse\x12\x36\n\x0brobot_state\x18\x01 \x01(\x0b\x32\x15.raybot.v1.RobotStateR\nrobotState\"\xf5\x01\n\nRobotState\x12<\n\rbattery_state\x18\x01 \x01(\x0b\x32\x17.raybot.v1.BatteryStateR\x0c\x62\x61tteryState\x12\x33\n\nwifi_state\x18\x02 \x01(\x0b\x32\x14.raybot.v1.WifiStateR\twifiState\x12\x36\n\x0bsensor_data\x18\x03 \x01(\x0b\x32\x15.raybot.v1.SensorDataR\nsensorData\x12<\n\rposition_data\x18\x04 \x01(\x0b\x32\x17.raybot.v1.PositionDataR\x0cpositionData\"\x98\x02\n\x0c\x42\x61tteryState\x12+\n\x11\x63harge_percentage\x18\x01 \x01(\x01R\x10\x63hargePercentage\x12\x18\n\x07\x63urrent\x18\x02 \x01(\x01R\x07\x63urrent\x12\x18\n\x07voltage\x18\x03 \x01(\x01R\x07voltage\x12 \n\x0btemperature\x18\x04 \x01(\x01R\x0btemperature\x12\x36\n\x06status\x18\x05 \x01(\x0e\x32\x1e.raybot.v1.BatteryState.StatusR\x06status\"M\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n\x0fSTATUS_CHARGING\x10\x01\x12\x16\n\x12STATUS_DISCHARGING\x10\x02\"\x89\x01\n\tWifiState\x12<\n\x0c\x63urrent_mode\x18\x01 \x01(\x0e\x32\x19.raybot.v1.WifiState.ModeR\x0b\x63urrentMode\x12\x12\n\x04ssid\x18\x02 \x01(\tR\x04ssid\"*\n\x04Mode\x12\x14\n\x10MODE_UNSPECIFIED\x10\x00\x12\x0c\n\x08MODE_STA\x10\x01\"}\n\nSensorData\x12%\n\x0e\x66ront_distance\x18\x01 \x01(\x01R\rfrontDistance\x12#\n\rrear_distance\x18\x02 \x01(\x01R\x0crearDistance\x12#\n\rdrop_distance\x18\x03 \x01(\x01R\x0c\x64ropDistance\"{\n\x0cPositionData\x12)\n\x10\x63urrent_location\x18\x01 \x01(\tR\x0f\x63urrentLocation\x12,\n\x0ftarget_location\x18\x02 \x01(\tH\x00R\x0etargetLocation\x88\x01\x01\x42\x12\n\x10_target_location2i\n\x11RobotStateService\x12T\n\rGetRobotState\x12\x1f.raybot.v1.GetRobotStateRequest\x1a .raybot.v1.GetRobotStateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raybot.v1.state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETROBOTSTATEREQUEST']._serialized_start=36
  _globals['_GETROBOTSTATEREQUEST']._serialized_end=58
  _globals['_GETROBOTSTATERESPONSE']._serialized_start=60
  _globals['_GETROBOTSTATERESPONSE']._serialized_end=139
  _globals['_ROBOTSTATE']._serialized_start=142
  _globals['_ROBOTSTATE']._serialized_end=387
  _globals['_BATTERYSTATE']._serialized_start=390
  _globals['_BATTERYSTATE']._serialized_end=670
  _globals['_BATTERYSTATE_STATUS']._serialized_start=593
  _globals['_BATTERYSTATE_STATUS']._serialized_end=670
  _globals['_WIFISTATE']._serialized_start=673
  _globals['_WIFISTATE']._serialized_end=810
  _globals['_WIFISTATE_MODE']._serialized_start=768
  _globals['_WIFISTATE_MODE']._serialized_end=810
  _globals['_SENSORDATA']._serialized_start=812
  _globals['_SENSORDATA']._serialized_end=937
  _globals['_POSITIONDATA']._serialized_start=939
  _globals['_POSITIONDATA']._serialized_end=1062
  _globals['_ROBOTSTATESERVICE']._serialized_start=1064
  _globals['_ROBOTSTATESERVICE']._serialized_end=1169
# @@protoc_insertion_point(module_scope)
