# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from raybot.v1 import system_pb2 as raybot_dot_v1_dot_system__pb2


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmergencyStop = channel.unary_unary(
                '/raybot.v1.SystemService/EmergencyStop',
                request_serializer=raybot_dot_v1_dot_system__pb2.EmergencyStopRequest.SerializeToString,
                response_deserializer=raybot_dot_v1_dot_system__pb2.EmergencyStopResponse.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmergencyStop(self, request, context):
        """EmergencyStop force robot stop all the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=raybot_dot_v1_dot_system__pb2.EmergencyStopRequest.FromString,
                    response_serializer=raybot_dot_v1_dot_system__pb2.EmergencyStopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raybot.v1.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raybot.v1.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raybot.v1.SystemService/EmergencyStop',
            raybot_dot_v1_dot_system__pb2.EmergencyStopRequest.SerializeToString,
            raybot_dot_v1_dot_system__pb2.EmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
