// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: distancesensor/v1/distance_sensor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDistanceSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistanceSensorRequest) Reset() {
	*x = GetDistanceSensorRequest{}
	mi := &file_distancesensor_v1_distance_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistanceSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceSensorRequest) ProtoMessage() {}

func (x *GetDistanceSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distancesensor_v1_distance_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceSensorRequest.ProtoReflect.Descriptor instead.
func (*GetDistanceSensorRequest) Descriptor() ([]byte, []int) {
	return file_distancesensor_v1_distance_sensor_proto_rawDescGZIP(), []int{0}
}

type GetDistanceSensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontDistance uint32                 `protobuf:"varint,1,opt,name=front_distance,json=frontDistance,proto3" json:"front_distance,omitempty"`
	BackDistance  uint32                 `protobuf:"varint,2,opt,name=back_distance,json=backDistance,proto3" json:"back_distance,omitempty"`
	DownDistance  uint32                 `protobuf:"varint,3,opt,name=down_distance,json=downDistance,proto3" json:"down_distance,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistanceSensorResponse) Reset() {
	*x = GetDistanceSensorResponse{}
	mi := &file_distancesensor_v1_distance_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistanceSensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistanceSensorResponse) ProtoMessage() {}

func (x *GetDistanceSensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distancesensor_v1_distance_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistanceSensorResponse.ProtoReflect.Descriptor instead.
func (*GetDistanceSensorResponse) Descriptor() ([]byte, []int) {
	return file_distancesensor_v1_distance_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistanceSensorResponse) GetFrontDistance() uint32 {
	if x != nil {
		return x.FrontDistance
	}
	return 0
}

func (x *GetDistanceSensorResponse) GetBackDistance() uint32 {
	if x != nil {
		return x.BackDistance
	}
	return 0
}

func (x *GetDistanceSensorResponse) GetDownDistance() uint32 {
	if x != nil {
		return x.DownDistance
	}
	return 0
}

func (x *GetDistanceSensorResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_distancesensor_v1_distance_sensor_proto protoreflect.FileDescriptor

const file_distancesensor_v1_distance_sensor_proto_rawDesc = "" +
	"\n" +
	"'distancesensor/v1/distance_sensor.proto\x12\x11distancesensor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n" +
	"\x18GetDistanceSensorRequest\"\xc7\x01\n" +
	"\x19GetDistanceSensorResponse\x12%\n" +
	"\x0efront_distance\x18\x01 \x01(\rR\rfrontDistance\x12#\n" +
	"\rback_distance\x18\x02 \x01(\rR\fbackDistance\x12#\n" +
	"\rdown_distance\x18\x03 \x01(\rR\fdownDistance\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB.Z,github.com/tbe-team/raybot/distancesensor/v1b\x06proto3"

var (
	file_distancesensor_v1_distance_sensor_proto_rawDescOnce sync.Once
	file_distancesensor_v1_distance_sensor_proto_rawDescData []byte
)

func file_distancesensor_v1_distance_sensor_proto_rawDescGZIP() []byte {
	file_distancesensor_v1_distance_sensor_proto_rawDescOnce.Do(func() {
		file_distancesensor_v1_distance_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distancesensor_v1_distance_sensor_proto_rawDesc), len(file_distancesensor_v1_distance_sensor_proto_rawDesc)))
	})
	return file_distancesensor_v1_distance_sensor_proto_rawDescData
}

var file_distancesensor_v1_distance_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_distancesensor_v1_distance_sensor_proto_goTypes = []any{
	(*GetDistanceSensorRequest)(nil),  // 0: distancesensor.v1.GetDistanceSensorRequest
	(*GetDistanceSensorResponse)(nil), // 1: distancesensor.v1.GetDistanceSensorResponse
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_distancesensor_v1_distance_sensor_proto_depIdxs = []int32{
	2, // 0: distancesensor.v1.GetDistanceSensorResponse.updated_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_distancesensor_v1_distance_sensor_proto_init() }
func file_distancesensor_v1_distance_sensor_proto_init() {
	if File_distancesensor_v1_distance_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distancesensor_v1_distance_sensor_proto_rawDesc), len(file_distancesensor_v1_distance_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_distancesensor_v1_distance_sensor_proto_goTypes,
		DependencyIndexes: file_distancesensor_v1_distance_sensor_proto_depIdxs,
		MessageInfos:      file_distancesensor_v1_distance_sensor_proto_msgTypes,
	}.Build()
	File_distancesensor_v1_distance_sensor_proto = out.File
	file_distancesensor_v1_distance_sensor_proto_goTypes = nil
	file_distancesensor_v1_distance_sensor_proto_depIdxs = nil
}
