// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: distancesensor/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistanceSensorService_GetDistanceSensor_FullMethodName = "/distancesensor.v1.DistanceSensorService/GetDistanceSensor"
)

// DistanceSensorServiceClient is the client API for DistanceSensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistanceSensorServiceClient interface {
	// GetDistanceSensor returns the current distance sensor information.
	GetDistanceSensor(ctx context.Context, in *GetDistanceSensorRequest, opts ...grpc.CallOption) (*GetDistanceSensorResponse, error)
}

type distanceSensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistanceSensorServiceClient(cc grpc.ClientConnInterface) DistanceSensorServiceClient {
	return &distanceSensorServiceClient{cc}
}

func (c *distanceSensorServiceClient) GetDistanceSensor(ctx context.Context, in *GetDistanceSensorRequest, opts ...grpc.CallOption) (*GetDistanceSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDistanceSensorResponse)
	err := c.cc.Invoke(ctx, DistanceSensorService_GetDistanceSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistanceSensorServiceServer is the server API for DistanceSensorService service.
// All implementations must embed UnimplementedDistanceSensorServiceServer
// for forward compatibility.
type DistanceSensorServiceServer interface {
	// GetDistanceSensor returns the current distance sensor information.
	GetDistanceSensor(context.Context, *GetDistanceSensorRequest) (*GetDistanceSensorResponse, error)
	mustEmbedUnimplementedDistanceSensorServiceServer()
}

// UnimplementedDistanceSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistanceSensorServiceServer struct{}

func (UnimplementedDistanceSensorServiceServer) GetDistanceSensor(context.Context, *GetDistanceSensorRequest) (*GetDistanceSensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistanceSensor not implemented")
}
func (UnimplementedDistanceSensorServiceServer) mustEmbedUnimplementedDistanceSensorServiceServer() {}
func (UnimplementedDistanceSensorServiceServer) testEmbeddedByValue()                               {}

// UnsafeDistanceSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistanceSensorServiceServer will
// result in compilation errors.
type UnsafeDistanceSensorServiceServer interface {
	mustEmbedUnimplementedDistanceSensorServiceServer()
}

func RegisterDistanceSensorServiceServer(s grpc.ServiceRegistrar, srv DistanceSensorServiceServer) {
	// If the following call pancis, it indicates UnimplementedDistanceSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistanceSensorService_ServiceDesc, srv)
}

func _DistanceSensorService_GetDistanceSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistanceSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceSensorServiceServer).GetDistanceSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistanceSensorService_GetDistanceSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceSensorServiceServer).GetDistanceSensor(ctx, req.(*GetDistanceSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistanceSensorService_ServiceDesc is the grpc.ServiceDesc for DistanceSensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistanceSensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distancesensor.v1.DistanceSensorService",
	HandlerType: (*DistanceSensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDistanceSensor",
			Handler:    _DistanceSensorService_GetDistanceSensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "distancesensor/v1/service.proto",
}
