// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: raybot/v1/lift_motor.proto

package raybotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetLiftMotorConfigurationRequest_Direction int32

const (
	// The direction is unknown
	SetLiftMotorConfigurationRequest_DIRECTION_UNSPECIFIED SetLiftMotorConfigurationRequest_Direction = 0
	// The motor is moving up
	SetLiftMotorConfigurationRequest_DIRECTION_UP SetLiftMotorConfigurationRequest_Direction = 1
	// The motor is moving down
	SetLiftMotorConfigurationRequest_DIRECTION_DOWN SetLiftMotorConfigurationRequest_Direction = 2
)

// Enum value maps for SetLiftMotorConfigurationRequest_Direction.
var (
	SetLiftMotorConfigurationRequest_Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_UP",
		2: "DIRECTION_DOWN",
	}
	SetLiftMotorConfigurationRequest_Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_UP":          1,
		"DIRECTION_DOWN":        2,
	}
)

func (x SetLiftMotorConfigurationRequest_Direction) Enum() *SetLiftMotorConfigurationRequest_Direction {
	p := new(SetLiftMotorConfigurationRequest_Direction)
	*p = x
	return p
}

func (x SetLiftMotorConfigurationRequest_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetLiftMotorConfigurationRequest_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_raybot_v1_lift_motor_proto_enumTypes[0].Descriptor()
}

func (SetLiftMotorConfigurationRequest_Direction) Type() protoreflect.EnumType {
	return &file_raybot_v1_lift_motor_proto_enumTypes[0]
}

func (x SetLiftMotorConfigurationRequest_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetLiftMotorConfigurationRequest_Direction.Descriptor instead.
func (SetLiftMotorConfigurationRequest_Direction) EnumDescriptor() ([]byte, []int) {
	return file_raybot_v1_lift_motor_proto_rawDescGZIP(), []int{0, 0}
}

type SetLiftMotorConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Distance calculated from the bottom of the robot to the top of the carry box.
	Distance float64 `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	// Direction of the motor
	Direction SetLiftMotorConfigurationRequest_Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=raybot.v1.SetLiftMotorConfigurationRequest_Direction" json:"direction,omitempty"`
}

func (x *SetLiftMotorConfigurationRequest) Reset() {
	*x = SetLiftMotorConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raybot_v1_lift_motor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLiftMotorConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLiftMotorConfigurationRequest) ProtoMessage() {}

func (x *SetLiftMotorConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raybot_v1_lift_motor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLiftMotorConfigurationRequest.ProtoReflect.Descriptor instead.
func (*SetLiftMotorConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_raybot_v1_lift_motor_proto_rawDescGZIP(), []int{0}
}

func (x *SetLiftMotorConfigurationRequest) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SetLiftMotorConfigurationRequest) GetDirection() SetLiftMotorConfigurationRequest_Direction {
	if x != nil {
		return x.Direction
	}
	return SetLiftMotorConfigurationRequest_DIRECTION_UNSPECIFIED
}

type SetLiftMotorConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLiftMotorConfigurationResponse) Reset() {
	*x = SetLiftMotorConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raybot_v1_lift_motor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLiftMotorConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLiftMotorConfigurationResponse) ProtoMessage() {}

func (x *SetLiftMotorConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raybot_v1_lift_motor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLiftMotorConfigurationResponse.ProtoReflect.Descriptor instead.
func (*SetLiftMotorConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_raybot_v1_lift_motor_proto_rawDescGZIP(), []int{1}
}

var File_raybot_v1_lift_motor_proto protoreflect.FileDescriptor

var file_raybot_v1_lift_motor_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x69, 0x66, 0x74,
	0x5f, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x61,
	0x79, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x22, 0xe1, 0x01, 0x0a, 0x20, 0x53, 0x65, 0x74, 0x4c,
	0x69, 0x66, 0x74, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x72, 0x61,
	0x79, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x66, 0x74, 0x4d,
	0x6f, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a,
	0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x49,
	0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x49, 0x52, 0x45, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x22, 0x23, 0x0a, 0x21, 0x53,
	0x65, 0x74, 0x4c, 0x69, 0x66, 0x74, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x8c, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x66, 0x74, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x78, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x66, 0x74,
	0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2b, 0x2e, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x4c, 0x69, 0x66, 0x74, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x4c,
	0x69, 0x66, 0x74, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0xa3, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2e, 0x76,
	0x31, 0x42, 0x0e, 0x4c, 0x69, 0x66, 0x74, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x62, 0x65, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2f, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x52, 0x61, 0x79, 0x62, 0x6f,
	0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x52, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x15, 0x52, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x52, 0x61, 0x79, 0x62, 0x6f,
	0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_raybot_v1_lift_motor_proto_rawDescOnce sync.Once
	file_raybot_v1_lift_motor_proto_rawDescData = file_raybot_v1_lift_motor_proto_rawDesc
)

func file_raybot_v1_lift_motor_proto_rawDescGZIP() []byte {
	file_raybot_v1_lift_motor_proto_rawDescOnce.Do(func() {
		file_raybot_v1_lift_motor_proto_rawDescData = protoimpl.X.CompressGZIP(file_raybot_v1_lift_motor_proto_rawDescData)
	})
	return file_raybot_v1_lift_motor_proto_rawDescData
}

var file_raybot_v1_lift_motor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raybot_v1_lift_motor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raybot_v1_lift_motor_proto_goTypes = []interface{}{
	(SetLiftMotorConfigurationRequest_Direction)(0), // 0: raybot.v1.SetLiftMotorConfigurationRequest.Direction
	(*SetLiftMotorConfigurationRequest)(nil),        // 1: raybot.v1.SetLiftMotorConfigurationRequest
	(*SetLiftMotorConfigurationResponse)(nil),       // 2: raybot.v1.SetLiftMotorConfigurationResponse
}
var file_raybot_v1_lift_motor_proto_depIdxs = []int32{
	0, // 0: raybot.v1.SetLiftMotorConfigurationRequest.direction:type_name -> raybot.v1.SetLiftMotorConfigurationRequest.Direction
	1, // 1: raybot.v1.LiftMotorService.SetLiftMotorConfiguration:input_type -> raybot.v1.SetLiftMotorConfigurationRequest
	2, // 2: raybot.v1.LiftMotorService.SetLiftMotorConfiguration:output_type -> raybot.v1.SetLiftMotorConfigurationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raybot_v1_lift_motor_proto_init() }
func file_raybot_v1_lift_motor_proto_init() {
	if File_raybot_v1_lift_motor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_raybot_v1_lift_motor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLiftMotorConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raybot_v1_lift_motor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLiftMotorConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_raybot_v1_lift_motor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raybot_v1_lift_motor_proto_goTypes,
		DependencyIndexes: file_raybot_v1_lift_motor_proto_depIdxs,
		EnumInfos:         file_raybot_v1_lift_motor_proto_enumTypes,
		MessageInfos:      file_raybot_v1_lift_motor_proto_msgTypes,
	}.Build()
	File_raybot_v1_lift_motor_proto = out.File
	file_raybot_v1_lift_motor_proto_rawDesc = nil
	file_raybot_v1_lift_motor_proto_goTypes = nil
	file_raybot_v1_lift_motor_proto_depIdxs = nil
}
