// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: raybot/v1/lift_motor.proto

package raybotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiftMotorService_SetLiftMotorConfiguration_FullMethodName = "/raybot.v1.LiftMotorService/SetLiftMotorConfiguration"
)

// LiftMotorServiceClient is the client API for LiftMotorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiftMotorServiceClient interface {
	SetLiftMotorConfiguration(ctx context.Context, in *SetLiftMotorConfigurationRequest, opts ...grpc.CallOption) (*SetLiftMotorConfigurationResponse, error)
}

type liftMotorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiftMotorServiceClient(cc grpc.ClientConnInterface) LiftMotorServiceClient {
	return &liftMotorServiceClient{cc}
}

func (c *liftMotorServiceClient) SetLiftMotorConfiguration(ctx context.Context, in *SetLiftMotorConfigurationRequest, opts ...grpc.CallOption) (*SetLiftMotorConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLiftMotorConfigurationResponse)
	err := c.cc.Invoke(ctx, LiftMotorService_SetLiftMotorConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiftMotorServiceServer is the server API for LiftMotorService service.
// All implementations must embed UnimplementedLiftMotorServiceServer
// for forward compatibility.
type LiftMotorServiceServer interface {
	SetLiftMotorConfiguration(context.Context, *SetLiftMotorConfigurationRequest) (*SetLiftMotorConfigurationResponse, error)
	mustEmbedUnimplementedLiftMotorServiceServer()
}

// UnimplementedLiftMotorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiftMotorServiceServer struct{}

func (UnimplementedLiftMotorServiceServer) SetLiftMotorConfiguration(context.Context, *SetLiftMotorConfigurationRequest) (*SetLiftMotorConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLiftMotorConfiguration not implemented")
}
func (UnimplementedLiftMotorServiceServer) mustEmbedUnimplementedLiftMotorServiceServer() {}
func (UnimplementedLiftMotorServiceServer) testEmbeddedByValue()                          {}

// UnsafeLiftMotorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiftMotorServiceServer will
// result in compilation errors.
type UnsafeLiftMotorServiceServer interface {
	mustEmbedUnimplementedLiftMotorServiceServer()
}

func RegisterLiftMotorServiceServer(s grpc.ServiceRegistrar, srv LiftMotorServiceServer) {
	// If the following call pancis, it indicates UnimplementedLiftMotorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiftMotorService_ServiceDesc, srv)
}

func _LiftMotorService_SetLiftMotorConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLiftMotorConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiftMotorServiceServer).SetLiftMotorConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiftMotorService_SetLiftMotorConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiftMotorServiceServer).SetLiftMotorConfiguration(ctx, req.(*SetLiftMotorConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiftMotorService_ServiceDesc is the grpc.ServiceDesc for LiftMotorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiftMotorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raybot.v1.LiftMotorService",
	HandlerType: (*LiftMotorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetLiftMotorConfiguration",
			Handler:    _LiftMotorService_SetLiftMotorConfiguration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raybot/v1/lift_motor.proto",
}
