// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: raybot/v1/system.proto

package raybotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmergencyStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmergencyStopRequest) Reset() {
	*x = EmergencyStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raybot_v1_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmergencyStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyStopRequest) ProtoMessage() {}

func (x *EmergencyStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raybot_v1_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyStopRequest.ProtoReflect.Descriptor instead.
func (*EmergencyStopRequest) Descriptor() ([]byte, []int) {
	return file_raybot_v1_system_proto_rawDescGZIP(), []int{0}
}

type EmergencyStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmergencyStopResponse) Reset() {
	*x = EmergencyStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raybot_v1_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmergencyStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyStopResponse) ProtoMessage() {}

func (x *EmergencyStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raybot_v1_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyStopResponse.ProtoReflect.Descriptor instead.
func (*EmergencyStopResponse) Descriptor() ([]byte, []int) {
	return file_raybot_v1_system_proto_rawDescGZIP(), []int{1}
}

var File_raybot_v1_system_proto protoreflect.FileDescriptor

var file_raybot_v1_system_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74,
	0x2e, 0x76, 0x31, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x45,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x65, 0x0a, 0x0d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x45, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e,
	0x63, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1f, 0x2e, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xa0, 0x01, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x62, 0x65, 0x2d, 0x74, 0x65, 0x61,
	0x6d, 0x2f, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72,
	0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2f,
	0x76, 0x31, 0x3b, 0x72, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x52, 0x58,
	0x58, 0xaa, 0x02, 0x09, 0x52, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09,
	0x52, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x52, 0x61, 0x79, 0x62,
	0x6f, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0a, 0x52, 0x61, 0x79, 0x62, 0x6f, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_raybot_v1_system_proto_rawDescOnce sync.Once
	file_raybot_v1_system_proto_rawDescData = file_raybot_v1_system_proto_rawDesc
)

func file_raybot_v1_system_proto_rawDescGZIP() []byte {
	file_raybot_v1_system_proto_rawDescOnce.Do(func() {
		file_raybot_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_raybot_v1_system_proto_rawDescData)
	})
	return file_raybot_v1_system_proto_rawDescData
}

var file_raybot_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raybot_v1_system_proto_goTypes = []interface{}{
	(*EmergencyStopRequest)(nil),  // 0: raybot.v1.EmergencyStopRequest
	(*EmergencyStopResponse)(nil), // 1: raybot.v1.EmergencyStopResponse
}
var file_raybot_v1_system_proto_depIdxs = []int32{
	0, // 0: raybot.v1.SystemService.EmergencyStop:input_type -> raybot.v1.EmergencyStopRequest
	1, // 1: raybot.v1.SystemService.EmergencyStop:output_type -> raybot.v1.EmergencyStopResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raybot_v1_system_proto_init() }
func file_raybot_v1_system_proto_init() {
	if File_raybot_v1_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_raybot_v1_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmergencyStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raybot_v1_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmergencyStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_raybot_v1_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raybot_v1_system_proto_goTypes,
		DependencyIndexes: file_raybot_v1_system_proto_depIdxs,
		MessageInfos:      file_raybot_v1_system_proto_msgTypes,
	}.Build()
	File_raybot_v1_system_proto = out.File
	file_raybot_v1_system_proto_rawDesc = nil
	file_raybot_v1_system_proto_goTypes = nil
	file_raybot_v1_system_proto_depIdxs = nil
}
