// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: location/v1/location.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{0}
}

type GetLocationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentLocation string                 `protobuf:"bytes,1,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_location_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *GetLocationResponse) GetCurrentLocation() string {
	if x != nil {
		return x.CurrentLocation
	}
	return ""
}

func (x *GetLocationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StreamLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLocationRequest) Reset() {
	*x = StreamLocationRequest{}
	mi := &file_location_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLocationRequest) ProtoMessage() {}

func (x *StreamLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLocationRequest.ProtoReflect.Descriptor instead.
func (*StreamLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{2}
}

type StreamLocationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentLocation string                 `protobuf:"bytes,1,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamLocationResponse) Reset() {
	*x = StreamLocationResponse{}
	mi := &file_location_v1_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLocationResponse) ProtoMessage() {}

func (x *StreamLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_v1_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLocationResponse.ProtoReflect.Descriptor instead.
func (*StreamLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_v1_location_proto_rawDescGZIP(), []int{3}
}

func (x *StreamLocationResponse) GetCurrentLocation() string {
	if x != nil {
		return x.CurrentLocation
	}
	return ""
}

func (x *StreamLocationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_location_v1_location_proto protoreflect.FileDescriptor

const file_location_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x1alocation/v1/location.proto\x12\vlocation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12GetLocationRequest\"{\n" +
	"\x13GetLocationResponse\x12)\n" +
	"\x10current_location\x18\x01 \x01(\tR\x0fcurrentLocation\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x17\n" +
	"\x15StreamLocationRequest\"~\n" +
	"\x16StreamLocationResponse\x12)\n" +
	"\x10current_location\x18\x01 \x01(\tR\x0fcurrentLocation\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB(Z&github.com/tbe-team/raybot/location/v1b\x06proto3"

var (
	file_location_v1_location_proto_rawDescOnce sync.Once
	file_location_v1_location_proto_rawDescData []byte
)

func file_location_v1_location_proto_rawDescGZIP() []byte {
	file_location_v1_location_proto_rawDescOnce.Do(func() {
		file_location_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)))
	})
	return file_location_v1_location_proto_rawDescData
}

var file_location_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_location_v1_location_proto_goTypes = []any{
	(*GetLocationRequest)(nil),     // 0: location.v1.GetLocationRequest
	(*GetLocationResponse)(nil),    // 1: location.v1.GetLocationResponse
	(*StreamLocationRequest)(nil),  // 2: location.v1.StreamLocationRequest
	(*StreamLocationResponse)(nil), // 3: location.v1.StreamLocationResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_location_v1_location_proto_depIdxs = []int32{
	4, // 0: location.v1.GetLocationResponse.updated_at:type_name -> google.protobuf.Timestamp
	4, // 1: location.v1.StreamLocationResponse.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_location_v1_location_proto_init() }
func file_location_v1_location_proto_init() {
	if File_location_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_v1_location_proto_rawDesc), len(file_location_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_location_v1_location_proto_goTypes,
		DependencyIndexes: file_location_v1_location_proto_depIdxs,
		MessageInfos:      file_location_v1_location_proto_msgTypes,
	}.Build()
	File_location_v1_location_proto = out.File
	file_location_v1_location_proto_goTypes = nil
	file_location_v1_location_proto_depIdxs = nil
}
