// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: location/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_location_v1_service_proto protoreflect.FileDescriptor

const file_location_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19location/v1/service.proto\x12\vlocation.v1\x1a\x1alocation/v1/location.proto2\xc4\x01\n" +
	"\x0fLocationService\x12R\n" +
	"\vGetLocation\x12\x1f.location.v1.GetLocationRequest\x1a .location.v1.GetLocationResponse\"\x00\x12]\n" +
	"\x0eStreamLocation\x12\".location.v1.StreamLocationRequest\x1a#.location.v1.StreamLocationResponse\"\x000\x01B(Z&github.com/tbe-team/raybot/location/v1b\x06proto3"

var file_location_v1_service_proto_goTypes = []any{
	(*GetLocationRequest)(nil),     // 0: location.v1.GetLocationRequest
	(*StreamLocationRequest)(nil),  // 1: location.v1.StreamLocationRequest
	(*GetLocationResponse)(nil),    // 2: location.v1.GetLocationResponse
	(*StreamLocationResponse)(nil), // 3: location.v1.StreamLocationResponse
}
var file_location_v1_service_proto_depIdxs = []int32{
	0, // 0: location.v1.LocationService.GetLocation:input_type -> location.v1.GetLocationRequest
	1, // 1: location.v1.LocationService.StreamLocation:input_type -> location.v1.StreamLocationRequest
	2, // 2: location.v1.LocationService.GetLocation:output_type -> location.v1.GetLocationResponse
	3, // 3: location.v1.LocationService.StreamLocation:output_type -> location.v1.StreamLocationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_location_v1_service_proto_init() }
func file_location_v1_service_proto_init() {
	if File_location_v1_service_proto != nil {
		return
	}
	file_location_v1_location_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_v1_service_proto_rawDesc), len(file_location_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_v1_service_proto_goTypes,
		DependencyIndexes: file_location_v1_service_proto_depIdxs,
	}.Build()
	File_location_v1_service_proto = out.File
	file_location_v1_service_proto_goTypes = nil
	file_location_v1_service_proto_depIdxs = nil
}
