// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: command/v1/command.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED    CommandType = 0
	CommandType_COMMAND_TYPE_STOP_MOVEMENT  CommandType = 1
	CommandType_COMMAND_TYPE_MOVE_FORWARD   CommandType = 2
	CommandType_COMMAND_TYPE_MOVE_BACKWARD  CommandType = 3
	CommandType_COMMAND_TYPE_MOVE_TO        CommandType = 4
	CommandType_COMMAND_TYPE_CARGO_OPEN     CommandType = 5
	CommandType_COMMAND_TYPE_CARGO_CLOSE    CommandType = 6
	CommandType_COMMAND_TYPE_CARGO_LIFT     CommandType = 7
	CommandType_COMMAND_TYPE_CARGO_LOWER    CommandType = 8
	CommandType_COMMAND_TYPE_CARGO_CHECK_QR CommandType = 9
	CommandType_COMMAND_TYPE_SCAN_LOCATION  CommandType = 10
	CommandType_COMMAND_TYPE_WAIT           CommandType = 11
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_TYPE_UNSPECIFIED",
		1:  "COMMAND_TYPE_STOP_MOVEMENT",
		2:  "COMMAND_TYPE_MOVE_FORWARD",
		3:  "COMMAND_TYPE_MOVE_BACKWARD",
		4:  "COMMAND_TYPE_MOVE_TO",
		5:  "COMMAND_TYPE_CARGO_OPEN",
		6:  "COMMAND_TYPE_CARGO_CLOSE",
		7:  "COMMAND_TYPE_CARGO_LIFT",
		8:  "COMMAND_TYPE_CARGO_LOWER",
		9:  "COMMAND_TYPE_CARGO_CHECK_QR",
		10: "COMMAND_TYPE_SCAN_LOCATION",
		11: "COMMAND_TYPE_WAIT",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":    0,
		"COMMAND_TYPE_STOP_MOVEMENT":  1,
		"COMMAND_TYPE_MOVE_FORWARD":   2,
		"COMMAND_TYPE_MOVE_BACKWARD":  3,
		"COMMAND_TYPE_MOVE_TO":        4,
		"COMMAND_TYPE_CARGO_OPEN":     5,
		"COMMAND_TYPE_CARGO_CLOSE":    6,
		"COMMAND_TYPE_CARGO_LIFT":     7,
		"COMMAND_TYPE_CARGO_LOWER":    8,
		"COMMAND_TYPE_CARGO_CHECK_QR": 9,
		"COMMAND_TYPE_SCAN_LOCATION":  10,
		"COMMAND_TYPE_WAIT":           11,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_command_v1_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_command_v1_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{0}
}

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_QUEUED      CommandStatus = 1
	CommandStatus_COMMAND_STATUS_PROCESSING  CommandStatus = 2
	CommandStatus_COMMAND_STATUS_SUCCEEDED   CommandStatus = 3
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 4
	CommandStatus_COMMAND_STATUS_CANCELED    CommandStatus = 5
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_QUEUED",
		2: "COMMAND_STATUS_PROCESSING",
		3: "COMMAND_STATUS_SUCCEEDED",
		4: "COMMAND_STATUS_FAILED",
		5: "COMMAND_STATUS_CANCELED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_QUEUED":      1,
		"COMMAND_STATUS_PROCESSING":  2,
		"COMMAND_STATUS_SUCCEEDED":   3,
		"COMMAND_STATUS_FAILED":      4,
		"COMMAND_STATUS_CANCELED":    5,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_command_v1_command_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_command_v1_command_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{1}
}

type CommandSource int32

const (
	CommandSource_COMMAND_SOURCE_UNSPECIFIED CommandSource = 0
	CommandSource_COMMAND_SOURCE_CLOUD       CommandSource = 1
	CommandSource_COMMAND_SOURCE_APP         CommandSource = 2
)

// Enum value maps for CommandSource.
var (
	CommandSource_name = map[int32]string{
		0: "COMMAND_SOURCE_UNSPECIFIED",
		1: "COMMAND_SOURCE_CLOUD",
		2: "COMMAND_SOURCE_APP",
	}
	CommandSource_value = map[string]int32{
		"COMMAND_SOURCE_UNSPECIFIED": 0,
		"COMMAND_SOURCE_CLOUD":       1,
		"COMMAND_SOURCE_APP":         2,
	}
)

func (x CommandSource) Enum() *CommandSource {
	p := new(CommandSource)
	*p = x
	return p
}

func (x CommandSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandSource) Descriptor() protoreflect.EnumDescriptor {
	return file_command_v1_command_proto_enumTypes[2].Descriptor()
}

func (CommandSource) Type() protoreflect.EnumType {
	return &file_command_v1_command_proto_enumTypes[2]
}

func (x CommandSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandSource.Descriptor instead.
func (CommandSource) EnumDescriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{2}
}

type GetCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequest) Reset() {
	*x = GetCommandRequest{}
	mi := &file_command_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequest) ProtoMessage() {}

func (x *GetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequest.ProtoReflect.Descriptor instead.
func (*GetCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommandRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=command.v1.CommandType" json:"type,omitempty"`
	Inputs        *CommandInputs         `protobuf:"bytes,2,opt,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandRequest) Reset() {
	*x = CreateCommandRequest{}
	mi := &file_command_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandRequest) ProtoMessage() {}

func (x *CreateCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommandRequest) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *CreateCommandRequest) GetInputs() *CommandInputs {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=command.v1.CommandType" json:"type,omitempty"`
	Status        CommandStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=command.v1.CommandStatus" json:"status,omitempty"`
	Source        CommandSource          `protobuf:"varint,4,opt,name=source,proto3,enum=command.v1.CommandSource" json:"source,omitempty"`
	Inputs        *CommandInputs         `protobuf:"bytes,5,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       *CommandOutputs        `protobuf:"bytes,6,opt,name=outputs,proto3" json:"outputs,omitempty"`
	Error         *string                `protobuf:"bytes,7,opt,name=error,proto3,oneof" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *Command) GetSource() CommandSource {
	if x != nil {
		return x.Source
	}
	return CommandSource_COMMAND_SOURCE_UNSPECIFIED
}

func (x *Command) GetInputs() *CommandInputs {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Command) GetOutputs() *CommandOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Command) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *Command) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Command) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Command) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Command) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandResponse) Reset() {
	*x = CreateCommandResponse{}
	mi := &file_command_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandResponse) ProtoMessage() {}

func (x *CreateCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandResponse.ProtoReflect.Descriptor instead.
func (*CreateCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type GetCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandResponse) Reset() {
	*x = GetCommandResponse{}
	mi := &file_command_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandResponse) ProtoMessage() {}

func (x *GetCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandResponse.ProtoReflect.Descriptor instead.
func (*GetCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_command_v1_command_proto protoreflect.FileDescriptor

const file_command_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x18command/v1/command.proto\x12\n" +
	"command.v1\x1a\x17command/v1/inputs.proto\x1a\x18command/v1/outputs.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11GetCommandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"v\n" +
	"\x14CreateCommandRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.command.v1.CommandTypeR\x04type\x121\n" +
	"\x06inputs\x18\x02 \x01(\v2\x19.command.v1.CommandInputsR\x06inputs\"\xd4\x04\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.command.v1.CommandTypeR\x04type\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.command.v1.CommandStatusR\x06status\x121\n" +
	"\x06source\x18\x04 \x01(\x0e2\x19.command.v1.CommandSourceR\x06source\x121\n" +
	"\x06inputs\x18\x05 \x01(\v2\x19.command.v1.CommandInputsR\x06inputs\x124\n" +
	"\aoutputs\x18\x06 \x01(\v2\x1a.command.v1.CommandOutputsR\aoutputs\x12\x19\n" +
	"\x05error\x18\a \x01(\tH\x00R\x05error\x88\x01\x01\x12>\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vcompletedAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06_errorB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"F\n" +
	"\x15CreateCommandResponse\x12-\n" +
	"\acommand\x18\x01 \x01(\v2\x13.command.v1.CommandR\acommand\"C\n" +
	"\x12GetCommandResponse\x12-\n" +
	"\acommand\x18\x01 \x01(\v2\x13.command.v1.CommandR\acommand*\xf2\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_STOP_MOVEMENT\x10\x01\x12\x1d\n" +
	"\x19COMMAND_TYPE_MOVE_FORWARD\x10\x02\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_MOVE_BACKWARD\x10\x03\x12\x18\n" +
	"\x14COMMAND_TYPE_MOVE_TO\x10\x04\x12\x1b\n" +
	"\x17COMMAND_TYPE_CARGO_OPEN\x10\x05\x12\x1c\n" +
	"\x18COMMAND_TYPE_CARGO_CLOSE\x10\x06\x12\x1b\n" +
	"\x17COMMAND_TYPE_CARGO_LIFT\x10\a\x12\x1c\n" +
	"\x18COMMAND_TYPE_CARGO_LOWER\x10\b\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_CARGO_CHECK_QR\x10\t\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_SCAN_LOCATION\x10\n" +
	"\x12\x15\n" +
	"\x11COMMAND_TYPE_WAIT\x10\v*\xbf\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMMAND_STATUS_QUEUED\x10\x01\x12\x1d\n" +
	"\x19COMMAND_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18COMMAND_STATUS_SUCCEEDED\x10\x03\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17COMMAND_STATUS_CANCELED\x10\x05*a\n" +
	"\rCommandSource\x12\x1e\n" +
	"\x1aCOMMAND_SOURCE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMMAND_SOURCE_CLOUD\x10\x01\x12\x16\n" +
	"\x12COMMAND_SOURCE_APP\x10\x02B'Z%github.com/tbe-team/raybot/command/v1b\x06proto3"

var (
	file_command_v1_command_proto_rawDescOnce sync.Once
	file_command_v1_command_proto_rawDescData []byte
)

func file_command_v1_command_proto_rawDescGZIP() []byte {
	file_command_v1_command_proto_rawDescOnce.Do(func() {
		file_command_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_v1_command_proto_rawDesc), len(file_command_v1_command_proto_rawDesc)))
	})
	return file_command_v1_command_proto_rawDescData
}

var file_command_v1_command_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_command_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_command_v1_command_proto_goTypes = []any{
	(CommandType)(0),              // 0: command.v1.CommandType
	(CommandStatus)(0),            // 1: command.v1.CommandStatus
	(CommandSource)(0),            // 2: command.v1.CommandSource
	(*GetCommandRequest)(nil),     // 3: command.v1.GetCommandRequest
	(*CreateCommandRequest)(nil),  // 4: command.v1.CreateCommandRequest
	(*Command)(nil),               // 5: command.v1.Command
	(*CreateCommandResponse)(nil), // 6: command.v1.CreateCommandResponse
	(*GetCommandResponse)(nil),    // 7: command.v1.GetCommandResponse
	(*CommandInputs)(nil),         // 8: command.v1.CommandInputs
	(*CommandOutputs)(nil),        // 9: command.v1.CommandOutputs
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_command_v1_command_proto_depIdxs = []int32{
	0,  // 0: command.v1.CreateCommandRequest.type:type_name -> command.v1.CommandType
	8,  // 1: command.v1.CreateCommandRequest.inputs:type_name -> command.v1.CommandInputs
	0,  // 2: command.v1.Command.type:type_name -> command.v1.CommandType
	1,  // 3: command.v1.Command.status:type_name -> command.v1.CommandStatus
	2,  // 4: command.v1.Command.source:type_name -> command.v1.CommandSource
	8,  // 5: command.v1.Command.inputs:type_name -> command.v1.CommandInputs
	9,  // 6: command.v1.Command.outputs:type_name -> command.v1.CommandOutputs
	10, // 7: command.v1.Command.started_at:type_name -> google.protobuf.Timestamp
	10, // 8: command.v1.Command.completed_at:type_name -> google.protobuf.Timestamp
	10, // 9: command.v1.Command.created_at:type_name -> google.protobuf.Timestamp
	10, // 10: command.v1.Command.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 11: command.v1.CreateCommandResponse.command:type_name -> command.v1.Command
	5,  // 12: command.v1.GetCommandResponse.command:type_name -> command.v1.Command
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_command_v1_command_proto_init() }
func file_command_v1_command_proto_init() {
	if File_command_v1_command_proto != nil {
		return
	}
	file_command_v1_inputs_proto_init()
	file_command_v1_outputs_proto_init()
	file_command_v1_command_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_v1_command_proto_rawDesc), len(file_command_v1_command_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_v1_command_proto_goTypes,
		DependencyIndexes: file_command_v1_command_proto_depIdxs,
		EnumInfos:         file_command_v1_command_proto_enumTypes,
		MessageInfos:      file_command_v1_command_proto_msgTypes,
	}.Build()
	File_command_v1_command_proto = out.File
	file_command_v1_command_proto_goTypes = nil
	file_command_v1_command_proto_depIdxs = nil
}
