// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: command/v1/inputs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveToInputs_Direction int32

const (
	MoveToInputs_DIRECTION_UNSPECIFIED MoveToInputs_Direction = 0
	MoveToInputs_DIRECTION_FORWARD     MoveToInputs_Direction = 1
	MoveToInputs_DIRECTION_BACKWARD    MoveToInputs_Direction = 2
)

// Enum value maps for MoveToInputs_Direction.
var (
	MoveToInputs_Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_FORWARD",
		2: "DIRECTION_BACKWARD",
	}
	MoveToInputs_Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_FORWARD":     1,
		"DIRECTION_BACKWARD":    2,
	}
)

func (x MoveToInputs_Direction) Enum() *MoveToInputs_Direction {
	p := new(MoveToInputs_Direction)
	*p = x
	return p
}

func (x MoveToInputs_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveToInputs_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_command_v1_inputs_proto_enumTypes[0].Descriptor()
}

func (MoveToInputs_Direction) Type() protoreflect.EnumType {
	return &file_command_v1_inputs_proto_enumTypes[0]
}

func (x MoveToInputs_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveToInputs_Direction.Descriptor instead.
func (MoveToInputs_Direction) EnumDescriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{4, 0}
}

type CommandInputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Inputs:
	//
	//	*CommandInputs_Stop
	//	*CommandInputs_MoveForward
	//	*CommandInputs_MoveBackward
	//	*CommandInputs_MoveTo
	//	*CommandInputs_CargoOpen
	//	*CommandInputs_CargoClose
	//	*CommandInputs_CargoLift
	//	*CommandInputs_CargoLower
	//	*CommandInputs_CargoCheckQr
	//	*CommandInputs_ScanLocation
	//	*CommandInputs_Wait
	Inputs        isCommandInputs_Inputs `protobuf_oneof:"inputs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInputs) Reset() {
	*x = CommandInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInputs) ProtoMessage() {}

func (x *CommandInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInputs.ProtoReflect.Descriptor instead.
func (*CommandInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{0}
}

func (x *CommandInputs) GetInputs() isCommandInputs_Inputs {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *CommandInputs) GetStop() *StopInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *CommandInputs) GetMoveForward() *MoveForwardInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_MoveForward); ok {
			return x.MoveForward
		}
	}
	return nil
}

func (x *CommandInputs) GetMoveBackward() *MoveBackwardInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_MoveBackward); ok {
			return x.MoveBackward
		}
	}
	return nil
}

func (x *CommandInputs) GetMoveTo() *MoveToInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_MoveTo); ok {
			return x.MoveTo
		}
	}
	return nil
}

func (x *CommandInputs) GetCargoOpen() *CargoOpenInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_CargoOpen); ok {
			return x.CargoOpen
		}
	}
	return nil
}

func (x *CommandInputs) GetCargoClose() *CargoCloseInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_CargoClose); ok {
			return x.CargoClose
		}
	}
	return nil
}

func (x *CommandInputs) GetCargoLift() *CargoLiftInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_CargoLift); ok {
			return x.CargoLift
		}
	}
	return nil
}

func (x *CommandInputs) GetCargoLower() *CargoLowerInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_CargoLower); ok {
			return x.CargoLower
		}
	}
	return nil
}

func (x *CommandInputs) GetCargoCheckQr() *CargoCheckQRInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_CargoCheckQr); ok {
			return x.CargoCheckQr
		}
	}
	return nil
}

func (x *CommandInputs) GetScanLocation() *ScanLocationInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_ScanLocation); ok {
			return x.ScanLocation
		}
	}
	return nil
}

func (x *CommandInputs) GetWait() *WaitInputs {
	if x != nil {
		if x, ok := x.Inputs.(*CommandInputs_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

type isCommandInputs_Inputs interface {
	isCommandInputs_Inputs()
}

type CommandInputs_Stop struct {
	Stop *StopInputs `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

type CommandInputs_MoveForward struct {
	MoveForward *MoveForwardInputs `protobuf:"bytes,3,opt,name=move_forward,json=moveForward,proto3,oneof"`
}

type CommandInputs_MoveBackward struct {
	MoveBackward *MoveBackwardInputs `protobuf:"bytes,4,opt,name=move_backward,json=moveBackward,proto3,oneof"`
}

type CommandInputs_MoveTo struct {
	MoveTo *MoveToInputs `protobuf:"bytes,5,opt,name=move_to,json=moveTo,proto3,oneof"`
}

type CommandInputs_CargoOpen struct {
	CargoOpen *CargoOpenInputs `protobuf:"bytes,6,opt,name=cargo_open,json=cargoOpen,proto3,oneof"`
}

type CommandInputs_CargoClose struct {
	CargoClose *CargoCloseInputs `protobuf:"bytes,7,opt,name=cargo_close,json=cargoClose,proto3,oneof"`
}

type CommandInputs_CargoLift struct {
	CargoLift *CargoLiftInputs `protobuf:"bytes,8,opt,name=cargo_lift,json=cargoLift,proto3,oneof"`
}

type CommandInputs_CargoLower struct {
	CargoLower *CargoLowerInputs `protobuf:"bytes,9,opt,name=cargo_lower,json=cargoLower,proto3,oneof"`
}

type CommandInputs_CargoCheckQr struct {
	CargoCheckQr *CargoCheckQRInputs `protobuf:"bytes,10,opt,name=cargo_check_qr,json=cargoCheckQr,proto3,oneof"`
}

type CommandInputs_ScanLocation struct {
	ScanLocation *ScanLocationInputs `protobuf:"bytes,11,opt,name=scan_location,json=scanLocation,proto3,oneof"`
}

type CommandInputs_Wait struct {
	Wait *WaitInputs `protobuf:"bytes,12,opt,name=wait,proto3,oneof"`
}

func (*CommandInputs_Stop) isCommandInputs_Inputs() {}

func (*CommandInputs_MoveForward) isCommandInputs_Inputs() {}

func (*CommandInputs_MoveBackward) isCommandInputs_Inputs() {}

func (*CommandInputs_MoveTo) isCommandInputs_Inputs() {}

func (*CommandInputs_CargoOpen) isCommandInputs_Inputs() {}

func (*CommandInputs_CargoClose) isCommandInputs_Inputs() {}

func (*CommandInputs_CargoLift) isCommandInputs_Inputs() {}

func (*CommandInputs_CargoLower) isCommandInputs_Inputs() {}

func (*CommandInputs_CargoCheckQr) isCommandInputs_Inputs() {}

func (*CommandInputs_ScanLocation) isCommandInputs_Inputs() {}

func (*CommandInputs_Wait) isCommandInputs_Inputs() {}

type StopInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInputs) Reset() {
	*x = StopInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInputs) ProtoMessage() {}

func (x *StopInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInputs.ProtoReflect.Descriptor instead.
func (*StopInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{1}
}

type MoveForwardInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MotorSpeed    uint32                 `protobuf:"varint,1,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveForwardInputs) Reset() {
	*x = MoveForwardInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveForwardInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveForwardInputs) ProtoMessage() {}

func (x *MoveForwardInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveForwardInputs.ProtoReflect.Descriptor instead.
func (*MoveForwardInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{2}
}

func (x *MoveForwardInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

type MoveBackwardInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MotorSpeed    uint32                 `protobuf:"varint,1,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveBackwardInputs) Reset() {
	*x = MoveBackwardInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveBackwardInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveBackwardInputs) ProtoMessage() {}

func (x *MoveBackwardInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveBackwardInputs.ProtoReflect.Descriptor instead.
func (*MoveBackwardInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{3}
}

func (x *MoveBackwardInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

type MoveToInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Direction     MoveToInputs_Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=command.v1.MoveToInputs_Direction" json:"direction,omitempty"`
	MotorSpeed    uint32                 `protobuf:"varint,3,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToInputs) Reset() {
	*x = MoveToInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToInputs) ProtoMessage() {}

func (x *MoveToInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToInputs.ProtoReflect.Descriptor instead.
func (*MoveToInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{4}
}

func (x *MoveToInputs) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *MoveToInputs) GetDirection() MoveToInputs_Direction {
	if x != nil {
		return x.Direction
	}
	return MoveToInputs_DIRECTION_UNSPECIFIED
}

func (x *MoveToInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

type CargoOpenInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MotorSpeed    uint32                 `protobuf:"varint,1,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoOpenInputs) Reset() {
	*x = CargoOpenInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoOpenInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoOpenInputs) ProtoMessage() {}

func (x *CargoOpenInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoOpenInputs.ProtoReflect.Descriptor instead.
func (*CargoOpenInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{5}
}

func (x *CargoOpenInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

type CargoCloseInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MotorSpeed    uint32                 `protobuf:"varint,1,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoCloseInputs) Reset() {
	*x = CargoCloseInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoCloseInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoCloseInputs) ProtoMessage() {}

func (x *CargoCloseInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoCloseInputs.ProtoReflect.Descriptor instead.
func (*CargoCloseInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{6}
}

func (x *CargoCloseInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

type CargoLiftInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	MotorSpeed    uint32                 `protobuf:"varint,2,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoLiftInputs) Reset() {
	*x = CargoLiftInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoLiftInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoLiftInputs) ProtoMessage() {}

func (x *CargoLiftInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoLiftInputs.ProtoReflect.Descriptor instead.
func (*CargoLiftInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{7}
}

func (x *CargoLiftInputs) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CargoLiftInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

type BottomObstacleTracking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnterDistance uint32                 `protobuf:"varint,1,opt,name=enter_distance,json=enterDistance,proto3" json:"enter_distance,omitempty"`
	ExitDistance  uint32                 `protobuf:"varint,2,opt,name=exit_distance,json=exitDistance,proto3" json:"exit_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BottomObstacleTracking) Reset() {
	*x = BottomObstacleTracking{}
	mi := &file_command_v1_inputs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BottomObstacleTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BottomObstacleTracking) ProtoMessage() {}

func (x *BottomObstacleTracking) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BottomObstacleTracking.ProtoReflect.Descriptor instead.
func (*BottomObstacleTracking) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{8}
}

func (x *BottomObstacleTracking) GetEnterDistance() uint32 {
	if x != nil {
		return x.EnterDistance
	}
	return 0
}

func (x *BottomObstacleTracking) GetExitDistance() uint32 {
	if x != nil {
		return x.ExitDistance
	}
	return 0
}

type CargoLowerInputs struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Position   uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	MotorSpeed uint32                 `protobuf:"varint,2,opt,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	// Deprecated: BottomObstacleTracking is no longer needed due to new command configuration.
	//
	// Deprecated: Marked as deprecated in command/v1/inputs.proto.
	BottomObstacleTracking *BottomObstacleTracking `protobuf:"bytes,3,opt,name=bottom_obstacle_tracking,json=bottomObstacleTracking,proto3" json:"bottom_obstacle_tracking,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CargoLowerInputs) Reset() {
	*x = CargoLowerInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoLowerInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoLowerInputs) ProtoMessage() {}

func (x *CargoLowerInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoLowerInputs.ProtoReflect.Descriptor instead.
func (*CargoLowerInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{9}
}

func (x *CargoLowerInputs) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CargoLowerInputs) GetMotorSpeed() uint32 {
	if x != nil {
		return x.MotorSpeed
	}
	return 0
}

// Deprecated: Marked as deprecated in command/v1/inputs.proto.
func (x *CargoLowerInputs) GetBottomObstacleTracking() *BottomObstacleTracking {
	if x != nil {
		return x.BottomObstacleTracking
	}
	return nil
}

type CargoCheckQRInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrCode        string                 `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoCheckQRInputs) Reset() {
	*x = CargoCheckQRInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoCheckQRInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoCheckQRInputs) ProtoMessage() {}

func (x *CargoCheckQRInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoCheckQRInputs.ProtoReflect.Descriptor instead.
func (*CargoCheckQRInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{10}
}

func (x *CargoCheckQRInputs) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type ScanLocationInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLocationInputs) Reset() {
	*x = ScanLocationInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLocationInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLocationInputs) ProtoMessage() {}

func (x *ScanLocationInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLocationInputs.ProtoReflect.Descriptor instead.
func (*ScanLocationInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{11}
}

type WaitInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitInputs) Reset() {
	*x = WaitInputs{}
	mi := &file_command_v1_inputs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitInputs) ProtoMessage() {}

func (x *WaitInputs) ProtoReflect() protoreflect.Message {
	mi := &file_command_v1_inputs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitInputs.ProtoReflect.Descriptor instead.
func (*WaitInputs) Descriptor() ([]byte, []int) {
	return file_command_v1_inputs_proto_rawDescGZIP(), []int{12}
}

func (x *WaitInputs) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_command_v1_inputs_proto protoreflect.FileDescriptor

const file_command_v1_inputs_proto_rawDesc = "" +
	"\n" +
	"\x17command/v1/inputs.proto\x12\n" +
	"command.v1\"\xc2\x05\n" +
	"\rCommandInputs\x12,\n" +
	"\x04stop\x18\x02 \x01(\v2\x16.command.v1.StopInputsH\x00R\x04stop\x12B\n" +
	"\fmove_forward\x18\x03 \x01(\v2\x1d.command.v1.MoveForwardInputsH\x00R\vmoveForward\x12E\n" +
	"\rmove_backward\x18\x04 \x01(\v2\x1e.command.v1.MoveBackwardInputsH\x00R\fmoveBackward\x123\n" +
	"\amove_to\x18\x05 \x01(\v2\x18.command.v1.MoveToInputsH\x00R\x06moveTo\x12<\n" +
	"\n" +
	"cargo_open\x18\x06 \x01(\v2\x1b.command.v1.CargoOpenInputsH\x00R\tcargoOpen\x12?\n" +
	"\vcargo_close\x18\a \x01(\v2\x1c.command.v1.CargoCloseInputsH\x00R\n" +
	"cargoClose\x12<\n" +
	"\n" +
	"cargo_lift\x18\b \x01(\v2\x1b.command.v1.CargoLiftInputsH\x00R\tcargoLift\x12?\n" +
	"\vcargo_lower\x18\t \x01(\v2\x1c.command.v1.CargoLowerInputsH\x00R\n" +
	"cargoLower\x12F\n" +
	"\x0ecargo_check_qr\x18\n" +
	" \x01(\v2\x1e.command.v1.CargoCheckQRInputsH\x00R\fcargoCheckQr\x12E\n" +
	"\rscan_location\x18\v \x01(\v2\x1e.command.v1.ScanLocationInputsH\x00R\fscanLocation\x12,\n" +
	"\x04wait\x18\f \x01(\v2\x16.command.v1.WaitInputsH\x00R\x04waitB\b\n" +
	"\x06inputs\"\f\n" +
	"\n" +
	"StopInputs\"4\n" +
	"\x11MoveForwardInputs\x12\x1f\n" +
	"\vmotor_speed\x18\x01 \x01(\rR\n" +
	"motorSpeed\"5\n" +
	"\x12MoveBackwardInputs\x12\x1f\n" +
	"\vmotor_speed\x18\x01 \x01(\rR\n" +
	"motorSpeed\"\xe4\x01\n" +
	"\fMoveToInputs\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12@\n" +
	"\tdirection\x18\x02 \x01(\x0e2\".command.v1.MoveToInputs.DirectionR\tdirection\x12\x1f\n" +
	"\vmotor_speed\x18\x03 \x01(\rR\n" +
	"motorSpeed\"U\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_FORWARD\x10\x01\x12\x16\n" +
	"\x12DIRECTION_BACKWARD\x10\x02\"2\n" +
	"\x0fCargoOpenInputs\x12\x1f\n" +
	"\vmotor_speed\x18\x01 \x01(\rR\n" +
	"motorSpeed\"3\n" +
	"\x10CargoCloseInputs\x12\x1f\n" +
	"\vmotor_speed\x18\x01 \x01(\rR\n" +
	"motorSpeed\"N\n" +
	"\x0fCargoLiftInputs\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x1f\n" +
	"\vmotor_speed\x18\x02 \x01(\rR\n" +
	"motorSpeed\"d\n" +
	"\x16BottomObstacleTracking\x12%\n" +
	"\x0eenter_distance\x18\x01 \x01(\rR\renterDistance\x12#\n" +
	"\rexit_distance\x18\x02 \x01(\rR\fexitDistance\"\xb1\x01\n" +
	"\x10CargoLowerInputs\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12\x1f\n" +
	"\vmotor_speed\x18\x02 \x01(\rR\n" +
	"motorSpeed\x12`\n" +
	"\x18bottom_obstacle_tracking\x18\x03 \x01(\v2\".command.v1.BottomObstacleTrackingB\x02\x18\x01R\x16bottomObstacleTracking\"-\n" +
	"\x12CargoCheckQRInputs\x12\x17\n" +
	"\aqr_code\x18\x01 \x01(\tR\x06qrCode\"\x14\n" +
	"\x12ScanLocationInputs\"-\n" +
	"\n" +
	"WaitInputs\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMsB+Z)github.com/tbe-team/raybot-api/command/v1b\x06proto3"

var (
	file_command_v1_inputs_proto_rawDescOnce sync.Once
	file_command_v1_inputs_proto_rawDescData []byte
)

func file_command_v1_inputs_proto_rawDescGZIP() []byte {
	file_command_v1_inputs_proto_rawDescOnce.Do(func() {
		file_command_v1_inputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_v1_inputs_proto_rawDesc), len(file_command_v1_inputs_proto_rawDesc)))
	})
	return file_command_v1_inputs_proto_rawDescData
}

var file_command_v1_inputs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_command_v1_inputs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_command_v1_inputs_proto_goTypes = []any{
	(MoveToInputs_Direction)(0),    // 0: command.v1.MoveToInputs.Direction
	(*CommandInputs)(nil),          // 1: command.v1.CommandInputs
	(*StopInputs)(nil),             // 2: command.v1.StopInputs
	(*MoveForwardInputs)(nil),      // 3: command.v1.MoveForwardInputs
	(*MoveBackwardInputs)(nil),     // 4: command.v1.MoveBackwardInputs
	(*MoveToInputs)(nil),           // 5: command.v1.MoveToInputs
	(*CargoOpenInputs)(nil),        // 6: command.v1.CargoOpenInputs
	(*CargoCloseInputs)(nil),       // 7: command.v1.CargoCloseInputs
	(*CargoLiftInputs)(nil),        // 8: command.v1.CargoLiftInputs
	(*BottomObstacleTracking)(nil), // 9: command.v1.BottomObstacleTracking
	(*CargoLowerInputs)(nil),       // 10: command.v1.CargoLowerInputs
	(*CargoCheckQRInputs)(nil),     // 11: command.v1.CargoCheckQRInputs
	(*ScanLocationInputs)(nil),     // 12: command.v1.ScanLocationInputs
	(*WaitInputs)(nil),             // 13: command.v1.WaitInputs
}
var file_command_v1_inputs_proto_depIdxs = []int32{
	2,  // 0: command.v1.CommandInputs.stop:type_name -> command.v1.StopInputs
	3,  // 1: command.v1.CommandInputs.move_forward:type_name -> command.v1.MoveForwardInputs
	4,  // 2: command.v1.CommandInputs.move_backward:type_name -> command.v1.MoveBackwardInputs
	5,  // 3: command.v1.CommandInputs.move_to:type_name -> command.v1.MoveToInputs
	6,  // 4: command.v1.CommandInputs.cargo_open:type_name -> command.v1.CargoOpenInputs
	7,  // 5: command.v1.CommandInputs.cargo_close:type_name -> command.v1.CargoCloseInputs
	8,  // 6: command.v1.CommandInputs.cargo_lift:type_name -> command.v1.CargoLiftInputs
	10, // 7: command.v1.CommandInputs.cargo_lower:type_name -> command.v1.CargoLowerInputs
	11, // 8: command.v1.CommandInputs.cargo_check_qr:type_name -> command.v1.CargoCheckQRInputs
	12, // 9: command.v1.CommandInputs.scan_location:type_name -> command.v1.ScanLocationInputs
	13, // 10: command.v1.CommandInputs.wait:type_name -> command.v1.WaitInputs
	0,  // 11: command.v1.MoveToInputs.direction:type_name -> command.v1.MoveToInputs.Direction
	9,  // 12: command.v1.CargoLowerInputs.bottom_obstacle_tracking:type_name -> command.v1.BottomObstacleTracking
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_command_v1_inputs_proto_init() }
func file_command_v1_inputs_proto_init() {
	if File_command_v1_inputs_proto != nil {
		return
	}
	file_command_v1_inputs_proto_msgTypes[0].OneofWrappers = []any{
		(*CommandInputs_Stop)(nil),
		(*CommandInputs_MoveForward)(nil),
		(*CommandInputs_MoveBackward)(nil),
		(*CommandInputs_MoveTo)(nil),
		(*CommandInputs_CargoOpen)(nil),
		(*CommandInputs_CargoClose)(nil),
		(*CommandInputs_CargoLift)(nil),
		(*CommandInputs_CargoLower)(nil),
		(*CommandInputs_CargoCheckQr)(nil),
		(*CommandInputs_ScanLocation)(nil),
		(*CommandInputs_Wait)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_v1_inputs_proto_rawDesc), len(file_command_v1_inputs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_v1_inputs_proto_goTypes,
		DependencyIndexes: file_command_v1_inputs_proto_depIdxs,
		EnumInfos:         file_command_v1_inputs_proto_enumTypes,
		MessageInfos:      file_command_v1_inputs_proto_msgTypes,
	}.Build()
	File_command_v1_inputs_proto = out.File
	file_command_v1_inputs_proto_goTypes = nil
	file_command_v1_inputs_proto_depIdxs = nil
}
