// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: command/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_command_v1_service_proto protoreflect.FileDescriptor

const file_command_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18command/v1/service.proto\x12\n" +
	"command.v1\x1a\x18command/v1/command.proto2\xb7\x01\n" +
	"\x0eCommandService\x12V\n" +
	"\rCreateCommand\x12 .command.v1.CreateCommandRequest\x1a!.command.v1.CreateCommandResponse\"\x00\x12M\n" +
	"\n" +
	"GetCommand\x12\x1d.command.v1.GetCommandRequest\x1a\x1e.command.v1.GetCommandResponse\"\x00B'Z%github.com/tbe-team/raybot/command/v1b\x06proto3"

var file_command_v1_service_proto_goTypes = []any{
	(*CreateCommandRequest)(nil),  // 0: command.v1.CreateCommandRequest
	(*GetCommandRequest)(nil),     // 1: command.v1.GetCommandRequest
	(*CreateCommandResponse)(nil), // 2: command.v1.CreateCommandResponse
	(*GetCommandResponse)(nil),    // 3: command.v1.GetCommandResponse
}
var file_command_v1_service_proto_depIdxs = []int32{
	0, // 0: command.v1.CommandService.CreateCommand:input_type -> command.v1.CreateCommandRequest
	1, // 1: command.v1.CommandService.GetCommand:input_type -> command.v1.GetCommandRequest
	2, // 2: command.v1.CommandService.CreateCommand:output_type -> command.v1.CreateCommandResponse
	3, // 3: command.v1.CommandService.GetCommand:output_type -> command.v1.GetCommandResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_command_v1_service_proto_init() }
func file_command_v1_service_proto_init() {
	if File_command_v1_service_proto != nil {
		return
	}
	file_command_v1_command_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_v1_service_proto_rawDesc), len(file_command_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_v1_service_proto_goTypes,
		DependencyIndexes: file_command_v1_service_proto_depIdxs,
	}.Build()
	File_command_v1_service_proto = out.File
	file_command_v1_service_proto_goTypes = nil
	file_command_v1_service_proto_depIdxs = nil
}
