// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: cargo/v1/cargo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCargoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCargoRequest) Reset() {
	*x = GetCargoRequest{}
	mi := &file_cargo_v1_cargo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCargoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoRequest) ProtoMessage() {}

func (x *GetCargoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoRequest.ProtoReflect.Descriptor instead.
func (*GetCargoRequest) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{0}
}

type GetCargoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsOpen         bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	QrCode         string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	BottomDistance uint32                 `protobuf:"varint,3,opt,name=bottom_distance,json=bottomDistance,proto3" json:"bottom_distance,omitempty"`
	HasItem        bool                   `protobuf:"varint,4,opt,name=has_item,json=hasItem,proto3" json:"has_item,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCargoResponse) Reset() {
	*x = GetCargoResponse{}
	mi := &file_cargo_v1_cargo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCargoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoResponse) ProtoMessage() {}

func (x *GetCargoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_v1_cargo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoResponse.ProtoReflect.Descriptor instead.
func (*GetCargoResponse) Descriptor() ([]byte, []int) {
	return file_cargo_v1_cargo_proto_rawDescGZIP(), []int{1}
}

func (x *GetCargoResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *GetCargoResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *GetCargoResponse) GetBottomDistance() uint32 {
	if x != nil {
		return x.BottomDistance
	}
	return 0
}

func (x *GetCargoResponse) GetHasItem() bool {
	if x != nil {
		return x.HasItem
	}
	return false
}

func (x *GetCargoResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_cargo_v1_cargo_proto protoreflect.FileDescriptor

const file_cargo_v1_cargo_proto_rawDesc = "" +
	"\n" +
	"\x14cargo/v1/cargo.proto\x12\bcargo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fGetCargoRequest\"\xc3\x01\n" +
	"\x10GetCargoResponse\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\x12'\n" +
	"\x0fbottom_distance\x18\x03 \x01(\rR\x0ebottomDistance\x12\x19\n" +
	"\bhas_item\x18\x04 \x01(\bR\ahasItem\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB%Z#github.com/tbe-team/raybot/cargo/v1b\x06proto3"

var (
	file_cargo_v1_cargo_proto_rawDescOnce sync.Once
	file_cargo_v1_cargo_proto_rawDescData []byte
)

func file_cargo_v1_cargo_proto_rawDescGZIP() []byte {
	file_cargo_v1_cargo_proto_rawDescOnce.Do(func() {
		file_cargo_v1_cargo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cargo_v1_cargo_proto_rawDesc), len(file_cargo_v1_cargo_proto_rawDesc)))
	})
	return file_cargo_v1_cargo_proto_rawDescData
}

var file_cargo_v1_cargo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cargo_v1_cargo_proto_goTypes = []any{
	(*GetCargoRequest)(nil),       // 0: cargo.v1.GetCargoRequest
	(*GetCargoResponse)(nil),      // 1: cargo.v1.GetCargoResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_cargo_v1_cargo_proto_depIdxs = []int32{
	2, // 0: cargo.v1.GetCargoResponse.updated_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cargo_v1_cargo_proto_init() }
func file_cargo_v1_cargo_proto_init() {
	if File_cargo_v1_cargo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cargo_v1_cargo_proto_rawDesc), len(file_cargo_v1_cargo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cargo_v1_cargo_proto_goTypes,
		DependencyIndexes: file_cargo_v1_cargo_proto_depIdxs,
		MessageInfos:      file_cargo_v1_cargo_proto_msgTypes,
	}.Build()
	File_cargo_v1_cargo_proto = out.File
	file_cargo_v1_cargo_proto_goTypes = nil
	file_cargo_v1_cargo_proto_depIdxs = nil
}
