// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sys/v1/sys_info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSysInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSysInfoRequest) Reset() {
	*x = GetSysInfoRequest{}
	mi := &file_sys_v1_sys_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSysInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysInfoRequest) ProtoMessage() {}

func (x *GetSysInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_v1_sys_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSysInfoRequest) Descriptor() ([]byte, []int) {
	return file_sys_v1_sys_info_proto_rawDescGZIP(), []int{0}
}

type GetSysInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalIp       string                 `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float32                `protobuf:"fixed32,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	TotalMemory   uint64                 `protobuf:"varint,4,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	Uptime        *durationpb.Duration   `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSysInfoResponse) Reset() {
	*x = GetSysInfoResponse{}
	mi := &file_sys_v1_sys_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSysInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysInfoResponse) ProtoMessage() {}

func (x *GetSysInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_v1_sys_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSysInfoResponse) Descriptor() ([]byte, []int) {
	return file_sys_v1_sys_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetSysInfoResponse) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *GetSysInfoResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetSysInfoResponse) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *GetSysInfoResponse) GetTotalMemory() uint64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *GetSysInfoResponse) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

var File_sys_v1_sys_info_proto protoreflect.FileDescriptor

const file_sys_v1_sys_info_proto_rawDesc = "" +
	"\n" +
	"\x15sys/v1/sys_info.proto\x12\x06sys.v1\x1a\x1egoogle/protobuf/duration.proto\"\x13\n" +
	"\x11GetSysInfoRequest\"\xc5\x01\n" +
	"\x12GetSysInfoResponse\x12\x19\n" +
	"\blocal_ip\x18\x01 \x01(\tR\alocalIp\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x02R\vmemoryUsage\x12!\n" +
	"\ftotal_memory\x18\x04 \x01(\x04R\vtotalMemory\x121\n" +
	"\x06uptime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x06uptimeB#Z!github.com/tbe-team/raybot/sys/v1b\x06proto3"

var (
	file_sys_v1_sys_info_proto_rawDescOnce sync.Once
	file_sys_v1_sys_info_proto_rawDescData []byte
)

func file_sys_v1_sys_info_proto_rawDescGZIP() []byte {
	file_sys_v1_sys_info_proto_rawDescOnce.Do(func() {
		file_sys_v1_sys_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_v1_sys_info_proto_rawDesc), len(file_sys_v1_sys_info_proto_rawDesc)))
	})
	return file_sys_v1_sys_info_proto_rawDescData
}

var file_sys_v1_sys_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sys_v1_sys_info_proto_goTypes = []any{
	(*GetSysInfoRequest)(nil),   // 0: sys.v1.GetSysInfoRequest
	(*GetSysInfoResponse)(nil),  // 1: sys.v1.GetSysInfoResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_sys_v1_sys_info_proto_depIdxs = []int32{
	2, // 0: sys.v1.GetSysInfoResponse.uptime:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sys_v1_sys_info_proto_init() }
func file_sys_v1_sys_info_proto_init() {
	if File_sys_v1_sys_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_v1_sys_info_proto_rawDesc), len(file_sys_v1_sys_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_v1_sys_info_proto_goTypes,
		DependencyIndexes: file_sys_v1_sys_info_proto_depIdxs,
		MessageInfos:      file_sys_v1_sys_info_proto_msgTypes,
	}.Build()
	File_sys_v1_sys_info_proto = out.File
	file_sys_v1_sys_info_proto_goTypes = nil
	file_sys_v1_sys_info_proto_depIdxs = nil
}
