// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: battery/v1/battery.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBatteryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatteryRequest) Reset() {
	*x = GetBatteryRequest{}
	mi := &file_battery_v1_battery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatteryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatteryRequest) ProtoMessage() {}

func (x *GetBatteryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_v1_battery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatteryRequest.ProtoReflect.Descriptor instead.
func (*GetBatteryRequest) Descriptor() ([]byte, []int) {
	return file_battery_v1_battery_proto_rawDescGZIP(), []int{0}
}

type GetBatteryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       uint32                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Temp          uint32                 `protobuf:"varint,2,opt,name=temp,proto3" json:"temp,omitempty"`
	Voltage       uint32                 `protobuf:"varint,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Cells         []uint32               `protobuf:"varint,4,rep,packed,name=cells,proto3" json:"cells,omitempty"`
	Percent       uint32                 `protobuf:"varint,5,opt,name=percent,proto3" json:"percent,omitempty"`
	Fault         uint32                 `protobuf:"varint,6,opt,name=fault,proto3" json:"fault,omitempty"`
	Health        uint32                 `protobuf:"varint,7,opt,name=health,proto3" json:"health,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatteryResponse) Reset() {
	*x = GetBatteryResponse{}
	mi := &file_battery_v1_battery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatteryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatteryResponse) ProtoMessage() {}

func (x *GetBatteryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_v1_battery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatteryResponse.ProtoReflect.Descriptor instead.
func (*GetBatteryResponse) Descriptor() ([]byte, []int) {
	return file_battery_v1_battery_proto_rawDescGZIP(), []int{1}
}

func (x *GetBatteryResponse) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *GetBatteryResponse) GetTemp() uint32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *GetBatteryResponse) GetVoltage() uint32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *GetBatteryResponse) GetCells() []uint32 {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *GetBatteryResponse) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *GetBatteryResponse) GetFault() uint32 {
	if x != nil {
		return x.Fault
	}
	return 0
}

func (x *GetBatteryResponse) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *GetBatteryResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetChargeSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChargeSettingRequest) Reset() {
	*x = GetChargeSettingRequest{}
	mi := &file_battery_v1_battery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargeSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargeSettingRequest) ProtoMessage() {}

func (x *GetChargeSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_v1_battery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargeSettingRequest.ProtoReflect.Descriptor instead.
func (*GetChargeSettingRequest) Descriptor() ([]byte, []int) {
	return file_battery_v1_battery_proto_rawDescGZIP(), []int{2}
}

type GetChargeSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLimit  uint32                 `protobuf:"varint,1,opt,name=current_limit,json=currentLimit,proto3" json:"current_limit,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChargeSettingResponse) Reset() {
	*x = GetChargeSettingResponse{}
	mi := &file_battery_v1_battery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChargeSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChargeSettingResponse) ProtoMessage() {}

func (x *GetChargeSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_v1_battery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChargeSettingResponse.ProtoReflect.Descriptor instead.
func (*GetChargeSettingResponse) Descriptor() ([]byte, []int) {
	return file_battery_v1_battery_proto_rawDescGZIP(), []int{3}
}

func (x *GetChargeSettingResponse) GetCurrentLimit() uint32 {
	if x != nil {
		return x.CurrentLimit
	}
	return 0
}

func (x *GetChargeSettingResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetChargeSettingResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetDischargeSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDischargeSettingRequest) Reset() {
	*x = GetDischargeSettingRequest{}
	mi := &file_battery_v1_battery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDischargeSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDischargeSettingRequest) ProtoMessage() {}

func (x *GetDischargeSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_v1_battery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDischargeSettingRequest.ProtoReflect.Descriptor instead.
func (*GetDischargeSettingRequest) Descriptor() ([]byte, []int) {
	return file_battery_v1_battery_proto_rawDescGZIP(), []int{4}
}

type GetDischargeSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLimit  uint32                 `protobuf:"varint,1,opt,name=current_limit,json=currentLimit,proto3" json:"current_limit,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDischargeSettingResponse) Reset() {
	*x = GetDischargeSettingResponse{}
	mi := &file_battery_v1_battery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDischargeSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDischargeSettingResponse) ProtoMessage() {}

func (x *GetDischargeSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_v1_battery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDischargeSettingResponse.ProtoReflect.Descriptor instead.
func (*GetDischargeSettingResponse) Descriptor() ([]byte, []int) {
	return file_battery_v1_battery_proto_rawDescGZIP(), []int{5}
}

func (x *GetDischargeSettingResponse) GetCurrentLimit() uint32 {
	if x != nil {
		return x.CurrentLimit
	}
	return 0
}

func (x *GetDischargeSettingResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetDischargeSettingResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_battery_v1_battery_proto protoreflect.FileDescriptor

const file_battery_v1_battery_proto_rawDesc = "" +
	"\n" +
	"\x18battery/v1/battery.proto\x12\n" +
	"battery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11GetBatteryRequest\"\xf5\x01\n" +
	"\x12GetBatteryResponse\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\rR\acurrent\x12\x12\n" +
	"\x04temp\x18\x02 \x01(\rR\x04temp\x12\x18\n" +
	"\avoltage\x18\x03 \x01(\rR\avoltage\x12\x14\n" +
	"\x05cells\x18\x04 \x03(\rR\x05cells\x12\x18\n" +
	"\apercent\x18\x05 \x01(\rR\apercent\x12\x14\n" +
	"\x05fault\x18\x06 \x01(\rR\x05fault\x12\x16\n" +
	"\x06health\x18\a \x01(\rR\x06health\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x19\n" +
	"\x17GetChargeSettingRequest\"\x94\x01\n" +
	"\x18GetChargeSettingResponse\x12#\n" +
	"\rcurrent_limit\x18\x01 \x01(\rR\fcurrentLimit\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1c\n" +
	"\x1aGetDischargeSettingRequest\"\x97\x01\n" +
	"\x1bGetDischargeSettingResponse\x12#\n" +
	"\rcurrent_limit\x18\x01 \x01(\rR\fcurrentLimit\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB'Z%github.com/tbe-team/raybot/battery/v1b\x06proto3"

var (
	file_battery_v1_battery_proto_rawDescOnce sync.Once
	file_battery_v1_battery_proto_rawDescData []byte
)

func file_battery_v1_battery_proto_rawDescGZIP() []byte {
	file_battery_v1_battery_proto_rawDescOnce.Do(func() {
		file_battery_v1_battery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battery_v1_battery_proto_rawDesc), len(file_battery_v1_battery_proto_rawDesc)))
	})
	return file_battery_v1_battery_proto_rawDescData
}

var file_battery_v1_battery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_battery_v1_battery_proto_goTypes = []any{
	(*GetBatteryRequest)(nil),           // 0: battery.v1.GetBatteryRequest
	(*GetBatteryResponse)(nil),          // 1: battery.v1.GetBatteryResponse
	(*GetChargeSettingRequest)(nil),     // 2: battery.v1.GetChargeSettingRequest
	(*GetChargeSettingResponse)(nil),    // 3: battery.v1.GetChargeSettingResponse
	(*GetDischargeSettingRequest)(nil),  // 4: battery.v1.GetDischargeSettingRequest
	(*GetDischargeSettingResponse)(nil), // 5: battery.v1.GetDischargeSettingResponse
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_battery_v1_battery_proto_depIdxs = []int32{
	6, // 0: battery.v1.GetBatteryResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 1: battery.v1.GetChargeSettingResponse.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: battery.v1.GetDischargeSettingResponse.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_battery_v1_battery_proto_init() }
func file_battery_v1_battery_proto_init() {
	if File_battery_v1_battery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battery_v1_battery_proto_rawDesc), len(file_battery_v1_battery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battery_v1_battery_proto_goTypes,
		DependencyIndexes: file_battery_v1_battery_proto_depIdxs,
		MessageInfos:      file_battery_v1_battery_proto_msgTypes,
	}.Build()
	File_battery_v1_battery_proto = out.File
	file_battery_v1_battery_proto_goTypes = nil
	file_battery_v1_battery_proto_depIdxs = nil
}
