// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: robotstate/v1/robotstate.proto

package v1

import (
	v1 "github.com/tbe-team/raybot-api/battery/v1"
	v11 "github.com/tbe-team/raybot-api/cargo/v1"
	v12 "github.com/tbe-team/raybot-api/distancesensor/v1"
	v15 "github.com/tbe-team/raybot-api/limitswitch/v1"
	v13 "github.com/tbe-team/raybot-api/location/v1"
	v14 "github.com/tbe-team/raybot-api/motor/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRobotStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRobotStateRequest) Reset() {
	*x = GetRobotStateRequest{}
	mi := &file_robotstate_v1_robotstate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRobotStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotStateRequest) ProtoMessage() {}

func (x *GetRobotStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotstate_v1_robotstate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotStateRequest.ProtoReflect.Descriptor instead.
func (*GetRobotStateRequest) Descriptor() ([]byte, []int) {
	return file_robotstate_v1_robotstate_proto_rawDescGZIP(), []int{0}
}

type GetRobotStateResponse struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	Battery          *v1.GetBatteryResponse          `protobuf:"bytes,1,opt,name=battery,proto3" json:"battery,omitempty"`
	ChargeSetting    *v1.GetChargeSettingResponse    `protobuf:"bytes,2,opt,name=charge_setting,json=chargeSetting,proto3" json:"charge_setting,omitempty"`
	DischargeSetting *v1.GetDischargeSettingResponse `protobuf:"bytes,3,opt,name=discharge_setting,json=dischargeSetting,proto3" json:"discharge_setting,omitempty"`
	Cargo            *v11.GetCargoResponse           `protobuf:"bytes,4,opt,name=cargo,proto3" json:"cargo,omitempty"`
	DistanceSensor   *v12.GetDistanceSensorResponse  `protobuf:"bytes,5,opt,name=distance_sensor,json=distanceSensor,proto3" json:"distance_sensor,omitempty"`
	Location         *v13.GetLocationResponse        `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	DriveMotor       *v14.GetDriveMotorResponse      `protobuf:"bytes,7,opt,name=drive_motor,json=driveMotor,proto3" json:"drive_motor,omitempty"`
	LiftMotor        *v14.GetLiftMotorResponse       `protobuf:"bytes,8,opt,name=lift_motor,json=liftMotor,proto3" json:"lift_motor,omitempty"`
	CargoDoorMotor   *v14.GetCargoDoorMotorResponse  `protobuf:"bytes,9,opt,name=cargo_door_motor,json=cargoDoorMotor,proto3" json:"cargo_door_motor,omitempty"`
	LimitSwitch_1    *v15.GetLimitSwitch1Response    `protobuf:"bytes,10,opt,name=limit_switch_1,json=limitSwitch1,proto3" json:"limit_switch_1,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRobotStateResponse) Reset() {
	*x = GetRobotStateResponse{}
	mi := &file_robotstate_v1_robotstate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRobotStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotStateResponse) ProtoMessage() {}

func (x *GetRobotStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotstate_v1_robotstate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotStateResponse.ProtoReflect.Descriptor instead.
func (*GetRobotStateResponse) Descriptor() ([]byte, []int) {
	return file_robotstate_v1_robotstate_proto_rawDescGZIP(), []int{1}
}

func (x *GetRobotStateResponse) GetBattery() *v1.GetBatteryResponse {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *GetRobotStateResponse) GetChargeSetting() *v1.GetChargeSettingResponse {
	if x != nil {
		return x.ChargeSetting
	}
	return nil
}

func (x *GetRobotStateResponse) GetDischargeSetting() *v1.GetDischargeSettingResponse {
	if x != nil {
		return x.DischargeSetting
	}
	return nil
}

func (x *GetRobotStateResponse) GetCargo() *v11.GetCargoResponse {
	if x != nil {
		return x.Cargo
	}
	return nil
}

func (x *GetRobotStateResponse) GetDistanceSensor() *v12.GetDistanceSensorResponse {
	if x != nil {
		return x.DistanceSensor
	}
	return nil
}

func (x *GetRobotStateResponse) GetLocation() *v13.GetLocationResponse {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetRobotStateResponse) GetDriveMotor() *v14.GetDriveMotorResponse {
	if x != nil {
		return x.DriveMotor
	}
	return nil
}

func (x *GetRobotStateResponse) GetLiftMotor() *v14.GetLiftMotorResponse {
	if x != nil {
		return x.LiftMotor
	}
	return nil
}

func (x *GetRobotStateResponse) GetCargoDoorMotor() *v14.GetCargoDoorMotorResponse {
	if x != nil {
		return x.CargoDoorMotor
	}
	return nil
}

func (x *GetRobotStateResponse) GetLimitSwitch_1() *v15.GetLimitSwitch1Response {
	if x != nil {
		return x.LimitSwitch_1
	}
	return nil
}

var File_robotstate_v1_robotstate_proto protoreflect.FileDescriptor

const file_robotstate_v1_robotstate_proto_rawDesc = "" +
	"\n" +
	"\x1erobotstate/v1/robotstate.proto\x12\rrobotstate.v1\x1a\x18battery/v1/battery.proto\x1a\x14cargo/v1/cargo.proto\x1a'distancesensor/v1/distance_sensor.proto\x1a!limitswitch/v1/limit_switch.proto\x1a\x1alocation/v1/location.proto\x1a\x14motor/v1/motor.proto\"\x16\n" +
	"\x14GetRobotStateRequest\"\xda\x05\n" +
	"\x15GetRobotStateResponse\x128\n" +
	"\abattery\x18\x01 \x01(\v2\x1e.battery.v1.GetBatteryResponseR\abattery\x12K\n" +
	"\x0echarge_setting\x18\x02 \x01(\v2$.battery.v1.GetChargeSettingResponseR\rchargeSetting\x12T\n" +
	"\x11discharge_setting\x18\x03 \x01(\v2'.battery.v1.GetDischargeSettingResponseR\x10dischargeSetting\x120\n" +
	"\x05cargo\x18\x04 \x01(\v2\x1a.cargo.v1.GetCargoResponseR\x05cargo\x12U\n" +
	"\x0fdistance_sensor\x18\x05 \x01(\v2,.distancesensor.v1.GetDistanceSensorResponseR\x0edistanceSensor\x12<\n" +
	"\blocation\x18\x06 \x01(\v2 .location.v1.GetLocationResponseR\blocation\x12@\n" +
	"\vdrive_motor\x18\a \x01(\v2\x1f.motor.v1.GetDriveMotorResponseR\n" +
	"driveMotor\x12=\n" +
	"\n" +
	"lift_motor\x18\b \x01(\v2\x1e.motor.v1.GetLiftMotorResponseR\tliftMotor\x12M\n" +
	"\x10cargo_door_motor\x18\t \x01(\v2#.motor.v1.GetCargoDoorMotorResponseR\x0ecargoDoorMotor\x12M\n" +
	"\x0elimit_switch_1\x18\n" +
	" \x01(\v2'.limitswitch.v1.GetLimitSwitch1ResponseR\flimitSwitch1B.Z,github.com/tbe-team/raybot-api/robotstate/v1b\x06proto3"

var (
	file_robotstate_v1_robotstate_proto_rawDescOnce sync.Once
	file_robotstate_v1_robotstate_proto_rawDescData []byte
)

func file_robotstate_v1_robotstate_proto_rawDescGZIP() []byte {
	file_robotstate_v1_robotstate_proto_rawDescOnce.Do(func() {
		file_robotstate_v1_robotstate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_robotstate_v1_robotstate_proto_rawDesc), len(file_robotstate_v1_robotstate_proto_rawDesc)))
	})
	return file_robotstate_v1_robotstate_proto_rawDescData
}

var file_robotstate_v1_robotstate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_robotstate_v1_robotstate_proto_goTypes = []any{
	(*GetRobotStateRequest)(nil),           // 0: robotstate.v1.GetRobotStateRequest
	(*GetRobotStateResponse)(nil),          // 1: robotstate.v1.GetRobotStateResponse
	(*v1.GetBatteryResponse)(nil),          // 2: battery.v1.GetBatteryResponse
	(*v1.GetChargeSettingResponse)(nil),    // 3: battery.v1.GetChargeSettingResponse
	(*v1.GetDischargeSettingResponse)(nil), // 4: battery.v1.GetDischargeSettingResponse
	(*v11.GetCargoResponse)(nil),           // 5: cargo.v1.GetCargoResponse
	(*v12.GetDistanceSensorResponse)(nil),  // 6: distancesensor.v1.GetDistanceSensorResponse
	(*v13.GetLocationResponse)(nil),        // 7: location.v1.GetLocationResponse
	(*v14.GetDriveMotorResponse)(nil),      // 8: motor.v1.GetDriveMotorResponse
	(*v14.GetLiftMotorResponse)(nil),       // 9: motor.v1.GetLiftMotorResponse
	(*v14.GetCargoDoorMotorResponse)(nil),  // 10: motor.v1.GetCargoDoorMotorResponse
	(*v15.GetLimitSwitch1Response)(nil),    // 11: limitswitch.v1.GetLimitSwitch1Response
}
var file_robotstate_v1_robotstate_proto_depIdxs = []int32{
	2,  // 0: robotstate.v1.GetRobotStateResponse.battery:type_name -> battery.v1.GetBatteryResponse
	3,  // 1: robotstate.v1.GetRobotStateResponse.charge_setting:type_name -> battery.v1.GetChargeSettingResponse
	4,  // 2: robotstate.v1.GetRobotStateResponse.discharge_setting:type_name -> battery.v1.GetDischargeSettingResponse
	5,  // 3: robotstate.v1.GetRobotStateResponse.cargo:type_name -> cargo.v1.GetCargoResponse
	6,  // 4: robotstate.v1.GetRobotStateResponse.distance_sensor:type_name -> distancesensor.v1.GetDistanceSensorResponse
	7,  // 5: robotstate.v1.GetRobotStateResponse.location:type_name -> location.v1.GetLocationResponse
	8,  // 6: robotstate.v1.GetRobotStateResponse.drive_motor:type_name -> motor.v1.GetDriveMotorResponse
	9,  // 7: robotstate.v1.GetRobotStateResponse.lift_motor:type_name -> motor.v1.GetLiftMotorResponse
	10, // 8: robotstate.v1.GetRobotStateResponse.cargo_door_motor:type_name -> motor.v1.GetCargoDoorMotorResponse
	11, // 9: robotstate.v1.GetRobotStateResponse.limit_switch_1:type_name -> limitswitch.v1.GetLimitSwitch1Response
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_robotstate_v1_robotstate_proto_init() }
func file_robotstate_v1_robotstate_proto_init() {
	if File_robotstate_v1_robotstate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robotstate_v1_robotstate_proto_rawDesc), len(file_robotstate_v1_robotstate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_robotstate_v1_robotstate_proto_goTypes,
		DependencyIndexes: file_robotstate_v1_robotstate_proto_depIdxs,
		MessageInfos:      file_robotstate_v1_robotstate_proto_msgTypes,
	}.Build()
	File_robotstate_v1_robotstate_proto = out.File
	file_robotstate_v1_robotstate_proto_goTypes = nil
	file_robotstate_v1_robotstate_proto_depIdxs = nil
}
