// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: robotstate/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_robotstate_v1_service_proto protoreflect.FileDescriptor

const file_robotstate_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1brobotstate/v1/service.proto\x12\rrobotstate.v1\x1a\x1erobotstate/v1/robotstate.proto2q\n" +
	"\x11RobotStateService\x12\\\n" +
	"\rGetRobotState\x12#.robotstate.v1.GetRobotStateRequest\x1a$.robotstate.v1.GetRobotStateResponse\"\x00B.Z,github.com/tbe-team/raybot-api/robotstate/v1b\x06proto3"

var file_robotstate_v1_service_proto_goTypes = []any{
	(*GetRobotStateRequest)(nil),  // 0: robotstate.v1.GetRobotStateRequest
	(*GetRobotStateResponse)(nil), // 1: robotstate.v1.GetRobotStateResponse
}
var file_robotstate_v1_service_proto_depIdxs = []int32{
	0, // 0: robotstate.v1.RobotStateService.GetRobotState:input_type -> robotstate.v1.GetRobotStateRequest
	1, // 1: robotstate.v1.RobotStateService.GetRobotState:output_type -> robotstate.v1.GetRobotStateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_robotstate_v1_service_proto_init() }
func file_robotstate_v1_service_proto_init() {
	if File_robotstate_v1_service_proto != nil {
		return
	}
	file_robotstate_v1_robotstate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robotstate_v1_service_proto_rawDesc), len(file_robotstate_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robotstate_v1_service_proto_goTypes,
		DependencyIndexes: file_robotstate_v1_service_proto_depIdxs,
	}.Build()
	File_robotstate_v1_service_proto = out.File
	file_robotstate_v1_service_proto_goTypes = nil
	file_robotstate_v1_service_proto_depIdxs = nil
}
