// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: robotstate/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotStateService_GetRobotState_FullMethodName = "/robotstate.v1.RobotStateService/GetRobotState"
)

// RobotStateServiceClient is the client API for RobotStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotStateServiceClient interface {
	// GetRobotState returns the current robot state.
	GetRobotState(ctx context.Context, in *GetRobotStateRequest, opts ...grpc.CallOption) (*GetRobotStateResponse, error)
}

type robotStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotStateServiceClient(cc grpc.ClientConnInterface) RobotStateServiceClient {
	return &robotStateServiceClient{cc}
}

func (c *robotStateServiceClient) GetRobotState(ctx context.Context, in *GetRobotStateRequest, opts ...grpc.CallOption) (*GetRobotStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRobotStateResponse)
	err := c.cc.Invoke(ctx, RobotStateService_GetRobotState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotStateServiceServer is the server API for RobotStateService service.
// All implementations must embed UnimplementedRobotStateServiceServer
// for forward compatibility.
type RobotStateServiceServer interface {
	// GetRobotState returns the current robot state.
	GetRobotState(context.Context, *GetRobotStateRequest) (*GetRobotStateResponse, error)
	mustEmbedUnimplementedRobotStateServiceServer()
}

// UnimplementedRobotStateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotStateServiceServer struct{}

func (UnimplementedRobotStateServiceServer) GetRobotState(context.Context, *GetRobotStateRequest) (*GetRobotStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobotState not implemented")
}
func (UnimplementedRobotStateServiceServer) mustEmbedUnimplementedRobotStateServiceServer() {}
func (UnimplementedRobotStateServiceServer) testEmbeddedByValue()                           {}

// UnsafeRobotStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotStateServiceServer will
// result in compilation errors.
type UnsafeRobotStateServiceServer interface {
	mustEmbedUnimplementedRobotStateServiceServer()
}

func RegisterRobotStateServiceServer(s grpc.ServiceRegistrar, srv RobotStateServiceServer) {
	// If the following call pancis, it indicates UnimplementedRobotStateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotStateService_ServiceDesc, srv)
}

func _RobotStateService_GetRobotState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRobotStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotStateServiceServer).GetRobotState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotStateService_GetRobotState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotStateServiceServer).GetRobotState(ctx, req.(*GetRobotStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RobotStateService_ServiceDesc is the grpc.ServiceDesc for RobotStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robotstate.v1.RobotStateService",
	HandlerType: (*RobotStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRobotState",
			Handler:    _RobotStateService_GetRobotState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "robotstate/v1/service.proto",
}
