// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: motor/v1/motor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDriveMotorResponse_Direction int32

const (
	GetDriveMotorResponse_DIRECTION_UNSPECIFIED GetDriveMotorResponse_Direction = 0
	GetDriveMotorResponse_DIRECTION_FORWARD     GetDriveMotorResponse_Direction = 1
	GetDriveMotorResponse_DIRECTION_BACKWARD    GetDriveMotorResponse_Direction = 2
)

// Enum value maps for GetDriveMotorResponse_Direction.
var (
	GetDriveMotorResponse_Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_FORWARD",
		2: "DIRECTION_BACKWARD",
	}
	GetDriveMotorResponse_Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_FORWARD":     1,
		"DIRECTION_BACKWARD":    2,
	}
)

func (x GetDriveMotorResponse_Direction) Enum() *GetDriveMotorResponse_Direction {
	p := new(GetDriveMotorResponse_Direction)
	*p = x
	return p
}

func (x GetDriveMotorResponse_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetDriveMotorResponse_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_motor_v1_motor_proto_enumTypes[0].Descriptor()
}

func (GetDriveMotorResponse_Direction) Type() protoreflect.EnumType {
	return &file_motor_v1_motor_proto_enumTypes[0]
}

func (x GetDriveMotorResponse_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetDriveMotorResponse_Direction.Descriptor instead.
func (GetDriveMotorResponse_Direction) EnumDescriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{1, 0}
}

type GetCargoDoorMotorResponse_Direction int32

const (
	GetCargoDoorMotorResponse_DIRECTION_UNSPECIFIED GetCargoDoorMotorResponse_Direction = 0
	GetCargoDoorMotorResponse_DIRECTION_OPEN        GetCargoDoorMotorResponse_Direction = 1
	GetCargoDoorMotorResponse_DIRECTION_CLOSE       GetCargoDoorMotorResponse_Direction = 2
)

// Enum value maps for GetCargoDoorMotorResponse_Direction.
var (
	GetCargoDoorMotorResponse_Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_OPEN",
		2: "DIRECTION_CLOSE",
	}
	GetCargoDoorMotorResponse_Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_OPEN":        1,
		"DIRECTION_CLOSE":       2,
	}
)

func (x GetCargoDoorMotorResponse_Direction) Enum() *GetCargoDoorMotorResponse_Direction {
	p := new(GetCargoDoorMotorResponse_Direction)
	*p = x
	return p
}

func (x GetCargoDoorMotorResponse_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCargoDoorMotorResponse_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_motor_v1_motor_proto_enumTypes[1].Descriptor()
}

func (GetCargoDoorMotorResponse_Direction) Type() protoreflect.EnumType {
	return &file_motor_v1_motor_proto_enumTypes[1]
}

func (x GetCargoDoorMotorResponse_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCargoDoorMotorResponse_Direction.Descriptor instead.
func (GetCargoDoorMotorResponse_Direction) EnumDescriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{5, 0}
}

type GetDriveMotorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveMotorRequest) Reset() {
	*x = GetDriveMotorRequest{}
	mi := &file_motor_v1_motor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveMotorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveMotorRequest) ProtoMessage() {}

func (x *GetDriveMotorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motor_v1_motor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveMotorRequest.ProtoReflect.Descriptor instead.
func (*GetDriveMotorRequest) Descriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{0}
}

type GetDriveMotorResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Direction     GetDriveMotorResponse_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=motor.v1.GetDriveMotorResponse_Direction" json:"direction,omitempty"`
	Speed         uint32                          `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	IsRunning     bool                            `protobuf:"varint,3,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	Enabled       bool                            `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpdatedAt     *timestamppb.Timestamp          `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveMotorResponse) Reset() {
	*x = GetDriveMotorResponse{}
	mi := &file_motor_v1_motor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveMotorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveMotorResponse) ProtoMessage() {}

func (x *GetDriveMotorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_motor_v1_motor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveMotorResponse.ProtoReflect.Descriptor instead.
func (*GetDriveMotorResponse) Descriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriveMotorResponse) GetDirection() GetDriveMotorResponse_Direction {
	if x != nil {
		return x.Direction
	}
	return GetDriveMotorResponse_DIRECTION_UNSPECIFIED
}

func (x *GetDriveMotorResponse) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *GetDriveMotorResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *GetDriveMotorResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetDriveMotorResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLiftMotorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiftMotorRequest) Reset() {
	*x = GetLiftMotorRequest{}
	mi := &file_motor_v1_motor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiftMotorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiftMotorRequest) ProtoMessage() {}

func (x *GetLiftMotorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motor_v1_motor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiftMotorRequest.ProtoReflect.Descriptor instead.
func (*GetLiftMotorRequest) Descriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{2}
}

type GetLiftMotorResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPosition uint32                 `protobuf:"varint,1,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	TargetPosition  uint32                 `protobuf:"varint,2,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	IsRunning       bool                   `protobuf:"varint,3,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	Enabled         bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLiftMotorResponse) Reset() {
	*x = GetLiftMotorResponse{}
	mi := &file_motor_v1_motor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiftMotorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiftMotorResponse) ProtoMessage() {}

func (x *GetLiftMotorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_motor_v1_motor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiftMotorResponse.ProtoReflect.Descriptor instead.
func (*GetLiftMotorResponse) Descriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{3}
}

func (x *GetLiftMotorResponse) GetCurrentPosition() uint32 {
	if x != nil {
		return x.CurrentPosition
	}
	return 0
}

func (x *GetLiftMotorResponse) GetTargetPosition() uint32 {
	if x != nil {
		return x.TargetPosition
	}
	return 0
}

func (x *GetLiftMotorResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *GetLiftMotorResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetLiftMotorResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetCargoDoorMotorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCargoDoorMotorRequest) Reset() {
	*x = GetCargoDoorMotorRequest{}
	mi := &file_motor_v1_motor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCargoDoorMotorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoDoorMotorRequest) ProtoMessage() {}

func (x *GetCargoDoorMotorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motor_v1_motor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoDoorMotorRequest.ProtoReflect.Descriptor instead.
func (*GetCargoDoorMotorRequest) Descriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{4}
}

type GetCargoDoorMotorResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Direction     GetCargoDoorMotorResponse_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=motor.v1.GetCargoDoorMotorResponse_Direction" json:"direction,omitempty"`
	Speed         uint32                              `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	IsRunning     bool                                `protobuf:"varint,3,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	Enabled       bool                                `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpdatedAt     *timestamppb.Timestamp              `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCargoDoorMotorResponse) Reset() {
	*x = GetCargoDoorMotorResponse{}
	mi := &file_motor_v1_motor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCargoDoorMotorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoDoorMotorResponse) ProtoMessage() {}

func (x *GetCargoDoorMotorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_motor_v1_motor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoDoorMotorResponse.ProtoReflect.Descriptor instead.
func (*GetCargoDoorMotorResponse) Descriptor() ([]byte, []int) {
	return file_motor_v1_motor_proto_rawDescGZIP(), []int{5}
}

func (x *GetCargoDoorMotorResponse) GetDirection() GetCargoDoorMotorResponse_Direction {
	if x != nil {
		return x.Direction
	}
	return GetCargoDoorMotorResponse_DIRECTION_UNSPECIFIED
}

func (x *GetCargoDoorMotorResponse) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *GetCargoDoorMotorResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *GetCargoDoorMotorResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetCargoDoorMotorResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_motor_v1_motor_proto protoreflect.FileDescriptor

const file_motor_v1_motor_proto_rawDesc = "" +
	"\n" +
	"\x14motor/v1/motor.proto\x12\bmotor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x16\n" +
	"\x14GetDriveMotorRequest\"\xc1\x02\n" +
	"\x15GetDriveMotorResponse\x12G\n" +
	"\tdirection\x18\x01 \x01(\x0e2).motor.v1.GetDriveMotorResponse.DirectionR\tdirection\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\rR\x05speed\x12\x1d\n" +
	"\n" +
	"is_running\x18\x03 \x01(\bR\tisRunning\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECTION_FORWARD\x10\x01\x12\x16\n" +
	"\x12DIRECTION_BACKWARD\x10\x02\"\x15\n" +
	"\x13GetLiftMotorRequest\"\xde\x01\n" +
	"\x14GetLiftMotorResponse\x12)\n" +
	"\x10current_position\x18\x01 \x01(\rR\x0fcurrentPosition\x12'\n" +
	"\x0ftarget_position\x18\x02 \x01(\rR\x0etargetPosition\x12\x1d\n" +
	"\n" +
	"is_running\x18\x03 \x01(\bR\tisRunning\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1a\n" +
	"\x18GetCargoDoorMotorRequest\"\xc3\x02\n" +
	"\x19GetCargoDoorMotorResponse\x12K\n" +
	"\tdirection\x18\x01 \x01(\x0e2-.motor.v1.GetCargoDoorMotorResponse.DirectionR\tdirection\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\rR\x05speed\x12\x1d\n" +
	"\n" +
	"is_running\x18\x03 \x01(\bR\tisRunning\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDIRECTION_OPEN\x10\x01\x12\x13\n" +
	"\x0fDIRECTION_CLOSE\x10\x02B)Z'github.com/tbe-team/raybot-api/motor/v1b\x06proto3"

var (
	file_motor_v1_motor_proto_rawDescOnce sync.Once
	file_motor_v1_motor_proto_rawDescData []byte
)

func file_motor_v1_motor_proto_rawDescGZIP() []byte {
	file_motor_v1_motor_proto_rawDescOnce.Do(func() {
		file_motor_v1_motor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_motor_v1_motor_proto_rawDesc), len(file_motor_v1_motor_proto_rawDesc)))
	})
	return file_motor_v1_motor_proto_rawDescData
}

var file_motor_v1_motor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_motor_v1_motor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_motor_v1_motor_proto_goTypes = []any{
	(GetDriveMotorResponse_Direction)(0),     // 0: motor.v1.GetDriveMotorResponse.Direction
	(GetCargoDoorMotorResponse_Direction)(0), // 1: motor.v1.GetCargoDoorMotorResponse.Direction
	(*GetDriveMotorRequest)(nil),             // 2: motor.v1.GetDriveMotorRequest
	(*GetDriveMotorResponse)(nil),            // 3: motor.v1.GetDriveMotorResponse
	(*GetLiftMotorRequest)(nil),              // 4: motor.v1.GetLiftMotorRequest
	(*GetLiftMotorResponse)(nil),             // 5: motor.v1.GetLiftMotorResponse
	(*GetCargoDoorMotorRequest)(nil),         // 6: motor.v1.GetCargoDoorMotorRequest
	(*GetCargoDoorMotorResponse)(nil),        // 7: motor.v1.GetCargoDoorMotorResponse
	(*timestamppb.Timestamp)(nil),            // 8: google.protobuf.Timestamp
}
var file_motor_v1_motor_proto_depIdxs = []int32{
	0, // 0: motor.v1.GetDriveMotorResponse.direction:type_name -> motor.v1.GetDriveMotorResponse.Direction
	8, // 1: motor.v1.GetDriveMotorResponse.updated_at:type_name -> google.protobuf.Timestamp
	8, // 2: motor.v1.GetLiftMotorResponse.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: motor.v1.GetCargoDoorMotorResponse.direction:type_name -> motor.v1.GetCargoDoorMotorResponse.Direction
	8, // 4: motor.v1.GetCargoDoorMotorResponse.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_motor_v1_motor_proto_init() }
func file_motor_v1_motor_proto_init() {
	if File_motor_v1_motor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_motor_v1_motor_proto_rawDesc), len(file_motor_v1_motor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_motor_v1_motor_proto_goTypes,
		DependencyIndexes: file_motor_v1_motor_proto_depIdxs,
		EnumInfos:         file_motor_v1_motor_proto_enumTypes,
		MessageInfos:      file_motor_v1_motor_proto_msgTypes,
	}.Build()
	File_motor_v1_motor_proto = out.File
	file_motor_v1_motor_proto_goTypes = nil
	file_motor_v1_motor_proto_depIdxs = nil
}
