// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: motor/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_motor_v1_service_proto protoreflect.FileDescriptor

const file_motor_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16motor/v1/service.proto\x12\bmotor.v1\x1a\x14motor/v1/motor.proto2\x93\x02\n" +
	"\fMotorService\x12R\n" +
	"\rGetDriveMotor\x12\x1e.motor.v1.GetDriveMotorRequest\x1a\x1f.motor.v1.GetDriveMotorResponse\"\x00\x12O\n" +
	"\fGetLiftMotor\x12\x1d.motor.v1.GetLiftMotorRequest\x1a\x1e.motor.v1.GetLiftMotorResponse\"\x00\x12^\n" +
	"\x11GetCargoDoorMotor\x12\".motor.v1.GetCargoDoorMotorRequest\x1a#.motor.v1.GetCargoDoorMotorResponse\"\x00B)Z'github.com/tbe-team/raybot-api/motor/v1b\x06proto3"

var file_motor_v1_service_proto_goTypes = []any{
	(*GetDriveMotorRequest)(nil),      // 0: motor.v1.GetDriveMotorRequest
	(*GetLiftMotorRequest)(nil),       // 1: motor.v1.GetLiftMotorRequest
	(*GetCargoDoorMotorRequest)(nil),  // 2: motor.v1.GetCargoDoorMotorRequest
	(*GetDriveMotorResponse)(nil),     // 3: motor.v1.GetDriveMotorResponse
	(*GetLiftMotorResponse)(nil),      // 4: motor.v1.GetLiftMotorResponse
	(*GetCargoDoorMotorResponse)(nil), // 5: motor.v1.GetCargoDoorMotorResponse
}
var file_motor_v1_service_proto_depIdxs = []int32{
	0, // 0: motor.v1.MotorService.GetDriveMotor:input_type -> motor.v1.GetDriveMotorRequest
	1, // 1: motor.v1.MotorService.GetLiftMotor:input_type -> motor.v1.GetLiftMotorRequest
	2, // 2: motor.v1.MotorService.GetCargoDoorMotor:input_type -> motor.v1.GetCargoDoorMotorRequest
	3, // 3: motor.v1.MotorService.GetDriveMotor:output_type -> motor.v1.GetDriveMotorResponse
	4, // 4: motor.v1.MotorService.GetLiftMotor:output_type -> motor.v1.GetLiftMotorResponse
	5, // 5: motor.v1.MotorService.GetCargoDoorMotor:output_type -> motor.v1.GetCargoDoorMotorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_motor_v1_service_proto_init() }
func file_motor_v1_service_proto_init() {
	if File_motor_v1_service_proto != nil {
		return
	}
	file_motor_v1_motor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_motor_v1_service_proto_rawDesc), len(file_motor_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_motor_v1_service_proto_goTypes,
		DependencyIndexes: file_motor_v1_service_proto_depIdxs,
	}.Build()
	File_motor_v1_service_proto = out.File
	file_motor_v1_service_proto_goTypes = nil
	file_motor_v1_service_proto_depIdxs = nil
}
