name: Bump Tag

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_RW_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
