name: PR CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  compile-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Generate protobuf
        run: |
          make tool-install
          make buf-go
      - name: Check for diff
        run: |
          if ! git diff --exit-code; then
            echo "⚠️ Code generation is outdated! Please run 'make buf-go' and commit the changes."
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
